### ISSUE TITLE
Restoring animator state tries to restore curve driven values

### ISSUE THREAD

**Issue by DirtyHippy00** [umasteeringgroup/UMA#1]
These are derived values and cannot be set - Unity will flag a warning.

in UMAGeneratorBase.cs, RestoreAnimatorState(Animator animator) wrapping the call with IsParameterControlledByCurve fixes issue.

				foreach(AnimatorControllerParameter param in parameters)
				{

                    if (!animator.IsParameterControlledByCurve (param.nameHash))
                    {
					    switch(param.type)
					    {
						    case AnimatorControllerParameterType.Bool:
							    animator.SetBool(param.nameHash, param.defaultBool);
							    break;
						    case AnimatorControllerParameterType.Float:
    						    animator.SetFloat(param.nameHash, param.defaultFloat);
							    break;
						    case AnimatorControllerParameterType.Int:
							    animator.SetInteger(param.nameHash, param.defaultInt);
							    break;
					    }
                    }
				}

**Comment by ecurtz** [comment]
Should the switch run when animator.IsParameterControlledByCurve() is true or false? Right now you have a ! in there, which seems to disagree with your comment.

**Comment by DirtyHippy00** [comment]
You do not want to update when controlled by curve - this is because Unity derives those values and doesn't want them explicitly set (and throws a warning if you do).

**Comment by virror** [comment]
Makes sense, let me have a look at it

**Comment by virror** [comment]
Fixed by:
https://github.com/umasteeringgroup/UMA/commit/93b3c32c8f7b37bce8a394c76400ff78e04f1c14
