### ISSUE TITLE
Renaming InternalDataStore/InGame/Resources to Resources_RENAMED causes editor exceptions and prevents project view from drawing in 2.71

### ISSUE THREAD

**Issue by DirtyHippy00** [umasteeringgroup/UMA#129]
I renamed the resources folder that I think DCS uses since I dont need it and it was adding a ton of stuff to my headless server builds.  Doing so caused exceptions when running (even an empty scene) and also prevented the project view from being drawn at all.

Repro:

1) Open up new project with UMA
2) Open empty scene
3) Rename InternalDataStore/InGame/Resources to Resources_RENAMED
4) Run empty scene
5) Note exceptions, project view doesn't draw anymore

NullReferenceException: Object reference not set to an instance of an object
UMA.UMAEditorUtilities.DrawItems (System.String guid, UnityEngine.Rect selectionRect) (at Assets/UMA/Core/Scripts/Editor/UMAEditorUtilities.cs:74)
UnityEditor.ProjectBrowser.OnGUIAssetCallback (System.Int32 instanceID, UnityEngine.Rect rect) (at C:/buildslave/unity/build/Editor/Mono/ProjectBrowser.cs:613)
UnityEditor.IMGUI.Controls.TreeViewController.DoItemGUI (UnityEditor.IMGUI.Controls.TreeViewItem item, System.Int32 row, System.Single rowWidth, System.Boolean hasFocus) (at

The exception is on line:
            AssetItem ai = UMAAssetIndexer.Instance.FromGuid(guid);
because the singleton doesn't exist.

Adding this trivially resolve the issue;

            if (UMAAssetIndexer.Instance == null)
                return;

**Comment by Jaimi** [comment]
This change is included in pull request 139.
