### ISSUE TITLE
Compile error with HairFadeCutout shader on Unity 2017.1 beta

### ISSUE THREAD

**Issue by mysticfall** [umasteeringgroup/UMA#13]
Building a project including UMA 2 fails on Unity 2017.1 beta with the following message:
>Duplicate system value semantic definition: input semantic 'VPOS' and input semantic 'SV_POSITION'

The offending line is [HairFadeCutout.shader#L136](https://github.com/umasteeringgroup/UMA/blob/c09b52149ea481dfa8b649c259e0fccc69badaf3/UMAProject/Assets/UMA/Examples/Main%20Examples/Assets/Shaders/HairFadeCutout.shader#L136), and I was able to workaround it by changing `VPOS` to `SV_POSITION` as suggested in a forum thread: 

* https://forum.unity3d.com/threads/tv-static-shader.354472/#post-2653488

**Comment by ross-p** [comment]
Same problem on Unity 5.6.1f1, only happens to me when I'm building for Android though.  Works fine in the editor, no errors.

**Comment by kenamis** [comment]
I pushed a fix for this in the uma26 branch.  Could either of you test it?

**Comment by mysticfall** [comment]
I'd like to, but I somehow managed to completely borked my Unity installation today so it won't even start up anymore. Urg...

I'll report the result as soon as I get it back to work.

**Comment by mysticfall** [comment]
@kenamis Just reinstalled Unity to fix the problem, and it seems that the `uma26` branch now compiles and runs without a problem on _2017.1b3_.

Thanks!

**Comment by ross-p** [comment]
@kenamis Confirmed working in Unity 5.6.1f1 on Android, thanks for the update.  :)

**Comment by kenamis** [comment]
cool, thanks for testing guys
