### ISSUE TITLE
Problem Building Project

### ISSUE THREAD

**Issue by rudenkovalim** [umasteeringgroup/UMA#130]
Hello! I'm having a problem when building a project. Here's the error:

NullReferenceException
UMA.UMA AssetIndexer.ForceSave () (at Assets / UMA / Core / Extensions / DynamicCharacterSystem / Scripts / UMAAssetIndexer.cs: 201)
UMA.UMAAssetIndexer.UnityEditor.Build.IPreprocessBuild.OnPreprocessBuild (BuildTarget target, System.String path) (at Assets / UMA / Core / Extensions / DynamicCharacterSystem / Scripts / UMAAssetIndexer.cs: 814)
UnityEditor.Build.BuildPipelineInterfaces.OnBuildPreProcess (BuildTarget platform, System.String path, Boolean strict) (at C: /buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs: 276)
UnityEditor.HostView: OnGUI ()

Here is the code from the script at the error location:

public void ForceSave ()
{
var st = StartTimer ();
EditorUtility.SetDirty (this.gameObject);
AssetDatabase.SaveAssets ();
StopTimer (st, "ForceSave");
}

An error in the SetDirty () method
What is not so configured or need to somehow rewrite in the script / project?
Help me please!

**Comment by kenamis** [comment]
What version on UMA and unity are you using? What platform are you building for?

**Comment by Jaimi** [comment]
Yeah, this sounds like an old bug from the original 2.6 release.

**Comment by rudenkovalim** [comment]
Thanks! Yes 2.6 version fixed this problem! https://github.com/umasteeringgroup/UMA/releases
