### ISSUE TITLE
UMA BUILD ISSUES

### ISSUE THREAD

**Issue by DrakeDane** [umasteeringgroup/UMA#132]
I have two issues that I am hoping someone can help with.

1. For some reason Build looks for UMA character save text files in a folder outside of the project. This means I have to copy files from the folder where they are auto saved in the Editor to this other folder, where the build expects to find them. This means I usually have to keep two sets of UMA files. How can I set the path to the UMA folder used in the Editor. Also why wouldn't these text files just be included in the build? Why does UMA have to find these in a folder outside of the project? Am I doing something wrong??

2.I use the above workaround from the main location where I do my game development. However, I will occasionally want to take build with me to a different office (different city). And so I usually have to be sure to copy the UMA text files and put them where I know the game expects to find them. Well, that seems to be working for the player character. But all of the other UMA characters are invisible! Apparently they are in the scene (you an even interact with the ones capable of interacting); but they are NOT being rendered! I will check folder. Not sure why this one character would load, but not the others. But, more importantly, the player character is totally naked! None of her gear is showing up that she should be wearing. When I try to equip gear, instead of displaying on the UMA, it ends up on the ground, under the character's feet!

How can I control where UMA saves my characters? How can I set UMA to save /load from the same folder used in the Editor? Also any ideas about what might be going on with my gear? That is a totally new issue that I have never seen before. But it has been a long time, since I have tried to run my game from a different computer.

Any feedback would be very appreciated!

**Comment by Jaimi** [comment]
it's simplest if you save your characters to a resource file, and then load them from resources.

As for your characters showing up naked in a build, thats usually because you have your items in the global library, and they don't have references. You should be able to open the global library window before you build, and see if that is the case.

**Comment by kenamis** [comment]
No reply.  Please open a new issue if you are still having a problem.
