### ISSUE TITLE
Trying to understand CombinedMesh creation

### ISSUE THREAD

**Issue by twobob** [umasteeringgroup/UMA#138]
Hi, 
I am trying to create a decimated pipeline

so I create a 
````
	/// <summary>
	/// Extended mesh combiner for UMA UMAMeshdata from slots with builtin decimation.
	/// </summary>
	public class UMADefaultMeshCombinerWithDecimate : UMAMeshCombiner
	{
````

and in it during the `	BuildCombineInstances();` method instead of just passing the various meshes I would like to 

A) get a copy of the UMAMesh object to decimate and ultimately combine.  What is the best practice here for Mesh cloning?

B) Know if this is the correct place to do such a thing - since early test reveal very confused material atlassing following decimation. (pictured)

Many thanks

![image](https://user-images.githubusercontent.com/915232/40880354-1a610136-66a7-11e8-9879-4155ccb889b5.png)

**Comment by twobob** [comment]
And the expected output
![image](https://user-images.githubusercontent.com/915232/40880377-8af94278-66a7-11e8-86f5-d2df4dcaf879.png)

**Comment by kenamis** [comment]
Hey,
Yes, the BuildCombineInstances is going to have references to the immutable mesh data that is on the mesh data assets.  You could loop through the combineInstances and make a copy of the mesh data.  That seems a little overkill though, I wonder if you could do your decimation algorithm in the skinned mesh combiner itself. 
If what you're trying to do is have LODs per slot mesh data, there already is a system in place for that to load up pre-authored LOD'd slots.  There's a basic component and scene for it called "UMASimpleLOD" and "UMA Core Demo - Texture LOD" respectively.  It may need some updating and definitely could be expanded on (it's on our list).
Would you like an invite to the UMA Slack channel so you can chat with us in realtime? If so, send me your email at kenan.chabuk@gmail.com and I'll invite you.

**Comment by twobob** [comment]
Yeah thanks man I did exactly what you say here.

Slow copying.
