### ISSUE TITLE
Add 'eye depth' and 'eye folds' DNA to default races (for Asian characters)

### ISSUE THREAD

**Issue by mysticfall** [umasteeringgroup/UMA#14]
For now, it's not easy (or even possible) to generate an authentic looking Asian characters with UMA, because it lacks such DNAs like 'eye depth' and 'eye folds'.

Considering the importance of providing ethnic diversity in such a project, it would be a significant improvement for a relatively small efforts if it could add such morphs to existing default races.

**Comment by Jaimi** [comment]
Available in Willb races
