### ISSUE TITLE
Erro no Unity de comando obsoleto:  Application.isWebPlayer. Queria saber um comando equivalente.

### ISSUE THREAD

**Issue by Hudson1212** [umasteeringgroup/UMA#145]
Messagem de Erro:
Assets/Store/StoreActions.cs(76,27): error CS0619: `UnityEngine.Application.isWebPlayer' is obsolete: `This property is deprecated and will be removed in a future version of Unity, Webplayer support has been removed since Unity 5.4'
Versão do unity: 2018.1.5f1
Código com erro:
...
else if (Application.isWebPlayer) {
    Application.ExternalEval ("window.open('" + checkoutUrl + "','_blank')");
...

**Comment by Jaimi** [comment]
Looks like this is part of this HexStrategy code.

https://github.com/swayamz/hexstrategy-mobile-app/blob/master/StoreActions.cs

Closing.
