### ISSUE TITLE
Expression creation error when o3n Female UMA race is used in bone pose

### ISSUE THREAD

**Issue by umutozkan** [umasteeringgroup/UMA#16]
If you drag mb female race UMA into bone pose's Source UMA field, it immediately gets the error in screenshot.

It somehow tries to add carpal4_R twice to the dictionary.

![image_720](https://user-images.githubusercontent.com/22751543/27244488-64498498-52ef-11e7-97cc-00568b33fb3d.png)

**Comment by umutozkan** [comment]
Error log:

ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[UnityEngine.Transform,UMA.PoseTools.UMABonePoseEditorContext+MirrorData].Add (UnityEngine.Transform key, MirrorData value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:207)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.FindMirroredTransforms (UnityEngine.Transform transform, System.Collections.Generic.Dictionary`2 mirrors) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:265)
UMA.PoseTools.UMABonePoseEditorContext.UpdateMirrors () (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:114)
UMA.PoseTools.UMABonePoseEditorContext.set_activeUMA (UMA.UMAData value) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditorContext.cs:77)
UMA.PoseTools.UMABonePoseEditor.OnInspectorGUI () (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMABonePoseEditor.cs:345)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1229)
UnityEditor.DockArea:OnGUI()

**Comment by kenamis** [comment]
is this still an issue?

**Comment by Jaimi** [comment]
Verified working in 2.11
