### ISSUE TITLE
DynamicCharacterAvatar: PerformRaceChange keepDNA/keepWardrobe/etc. bug

### ISSUE THREAD

**Issue by CannibalVox** [umasteeringgroup/UMA#177]
When calling PerformRaceChange, you can pass in flags to keep the current DNA, wardrobe, etc.  If they are not provided, the checkboxes on the DynamicCharacterAvatar are used.  For each keep* flag, a load* flag is removed from a LoadOptions value, and then the resulting LoadOptions value is passed along to ImportSettings.  However, if all flags are removed from the LoadOptions in this manner, what remains is LoadOptions.useDefaults, which causes all values to be loaded instead of none.

Other flag types in UMA have a None flag that can be applied when using this strategy, to ensure that what remains after all flags are removed is None.  However, LoadOptions does not have a None flag.  This needs to be changed.

Removing flags from LoadOptions: https://github.com/umasteeringgroup/UMA/blob/master/UMAProject/Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/DynamicCharacterAvatar.cs#L628

Calling ImportSettingsCO: https://github.com/umasteeringgroup/UMA/blob/master/UMAProject/Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/DynamicCharacterAvatar.cs#L690

Use defaults if LoadOptions is useDefaults: https://github.com/umasteeringgroup/UMA/blob/master/UMAProject/Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/DynamicCharacterAvatar.cs#L2118

**Comment by Jaimi** [comment]
Closing old issues
