### ISSUE TITLE
TestCustomizerDD.cs error

### ISSUE THREAD

**Issue by taciturnsays** [umasteeringgroup/UMA#188]
Happy new year!
I am using unity 2018.1.0f2 and imported the UMA project wich gives me 4 errors driven by the same issue, the EventTrigger, preventing me to compile, here they follow:

**Assets/UMA/Examples/Extensions Examples/DynamicCharacterSystem/Scripts/Scene2and3/TestCustomizerDD.cs:**

 **Line (467,18):** error CS0426: The nested type `Entry' does not exist in the type `EventTrigger'

**Line (468,5):** error CS0841 A local variable `entry' cannot be used before it is declared

**Line (469,5):** error CS0841: A local variable `entry' cannot be used before it is declared

**Line (470,13):** error CS1061: Type `EventTrigger' does not contain a definition for `triggers' and no extension method `triggers' of type `EventTrigger' could be found. Are you missing an assembly reference?

**Comment by kenamis** [comment]
Happy new year!
I opened up uma 2.8 RC in unity 2018.1.0f2 and none of those errors.  In UMA 2.7, those lines are the same.  Did you modify the file in some way?

**Comment by Jaimi** [comment]
Unable to duplicate. EventTrigger is a unity class - I suspect there is something wrong with the project, either a duplicate EventTrigger class declared in the global namespace, or the install is corrupted.
