### ISSUE TITLE
Add support for HDRP and LWRP (Feature Request)

### ISSUE THREAD

**Issue by wirelessdreamer** [umasteeringgroup/UMA#192]
Great job on UMA so far. Any eta on adding support for LWRP and HDRP materials so UMA can be used with the new render systems? With some guidance I should be able to help on work and testing in that area.

**Comment by Jaimi** [comment]
There are issues with the atlas shaders and/or the texture merge - we will be looking into this after we have stabilized 2.8 for release (2018.3 is being a particularly rough upgrade)

**Comment by wirelessdreamer** [comment]
Awesome, thanks for the update.

**Comment by Jaimi** [comment]
This feature will be included in 2.9, kenamis has a test version working. I'll close this out, and you should see a beta available with this functionality when w

**Comment by wirelessdreamer** [comment]
Awesome, thanks :)

**Comment by wirelessdreamer** [comment]
@Jaimi how could I get the test version? I'd like to give it a try, i'm currently using the 2.8 git version.

**Comment by Jaimi** [comment]
kenamis created a branch for it: feature-HDRP,  select the code tab here in the GitHub project, change the branch and download the zip uding the "clone or download" button.

**Comment by imjusthere** [comment]
Any idea when 2.9 will be available?

**Comment by Jaimi** [comment]
No idea, sorry.

**Comment by PinoEire** [comment]
I just tested the Feature-HDRP branch but it doesn't seem to work either: any pointers about how to use it?

**Comment by Jaimi** [comment]
You should use the Develop branch - it has all the latest updates and HDRP support

**Comment by kenamis** [comment]
@PinoEire You also need to convert your uma materials, overlays, slots to use the new shaders in the RP you are using.  I have a sample package for uma default for HD here; https://github.com/kenamis/UMAHumanHD

**Comment by daschatten** [comment]
@kenamis Any specific instruction to get this running?

- Checked out dev branch today
- Checked out kenamis HD repo a week ago
- Copied UMA and UMA_HD folders to a new HDRP project
- Put in UMA_DCS
- Put in UMADynamicCharacterAvatar
- Rebuilt UMA Global Library
- Switched active race to HumanMaleHD on avatar
- Hit Play
- Got a strange stretched something instead of an avatar. Looks the same as with 2.8.1 and kenamis HD

**Comment by wirelessdreamer** [comment]
That sounds like the issue I had, try this.

@daschatten Find the directory with your UMA Materials in
![image](https://user-images.githubusercontent.com/140221/61129053-950e7580-a481-11e9-8566-760fb115de73.png)
edit the generated texture settings
the first one should be BaseMap, not MainTex
![image](https://user-images.githubusercontent.com/140221/61129176-cc7d2200-a481-11e9-92d9-2970b5c9d43e.png)
use the drop down to update it

**Comment by daschatten** [comment]
@wirelessdreamer I use kenamis hd package and the uma material looks this, especially the diffuse keyword is different to yours. Which hdrp version do you use? For me it's 5.7.2

![grafik](https://user-images.githubusercontent.com/2094680/61133234-53032500-a4bd-11e9-9ae6-d737e393d6a0.png)

**Comment by wirelessdreamer** [comment]
I'm using lwrp, never touched hdrp yet

**Comment by kenamis** [comment]
Do you have any console errors or warnings? Can you post a screenshot of
what your issue loops like?

**Comment by kenamis** [comment]
I think hdrp requires linear color space too. Did you set that in your
project settings?

**Comment by daschatten** [comment]
> I think hdrp requires linear color space too. Did you set that in your project settings?

Yep, it's set (by default).

**Comment by daschatten** [comment]
> Do you have any console errors or warnings? Can you post a screenshot of what your issue loops like?

No warnings or errors. Here is a screenshot:

![grafik](https://user-images.githubusercontent.com/2094680/61188608-f6049c00-a681-11e9-973c-a10138c425ee.png)

I'm using Unity 2019.1.8 with HDRP template.

**Comment by kenamis** [comment]
If you use the builtin Renderer do you have any problems? Your issue
doesn't look like anything specific to the SRP support (it doesn't affect
the mesh generation).

**Comment by daschatten** [comment]
If i use a new 3D project template in 2019.1.8 and add uma dev branch there is no issue.

**Comment by daschatten** [comment]
![grafik](https://user-images.githubusercontent.com/2094680/61206121-13714e80-a6f2-11e9-96ca-1467e49b04ba.png)

**Comment by daschatten** [comment]
I posted another picture in slack as jaimi asked if the character is wrapped in a ear:
![image](https://user-images.githubusercontent.com/2094680/61206181-3e5ba280-a6f2-11e9-943d-b0e1d9a88e0c.png)

**Comment by daschatten** [comment]
Ok, got it working:

![grafik](https://user-images.githubusercontent.com/2094680/61279888-429dc380-a7b7-11e9-8c3c-8901d26733bc.png)

It was really simple, i just replaced the unity material in those four files with the one from kenamis hd and set the shader channels correctly.

![grafik](https://user-images.githubusercontent.com/2094680/61280004-72e56200-a7b7-11e9-919e-05ae60a9e9b6.png)
![grafik](https://user-images.githubusercontent.com/2094680/61280066-8bee1300-a7b7-11e9-913b-720d7da31245.png)

There must be something wrong in your package @kenamis.

**Comment by daschatten** [comment]
Note: I used Unity 2019.1.8 and UMA develop branch!

**Comment by kenamis** [comment]
Ok thanks.  I'll check it out and update it.

**Comment by kenamis** [comment]
the HD repo's uma material is correct;
https://github.com/kenamis/UMAHumanHD/blob/master/UMAHumanHD/Assets/UMA_HD/HumanSharedHD/HDMaterial/UMA_Lit.asset

You said "It was really simple, i just replaced the unity material in those four files with the one from kenamis hd and set the shader channels correctly", were you not using the new HD race that has that new uma material already set?  If not, then I think the issues you were seeing would be the outcome.

**Comment by daschatten** [comment]
At first i tried the new HD race but that resulted in the distorted textures as shown above. Finally i just replaced the unity material in those four default UMA materials (not the HD ones) and set it to yours (Simple material with HDRP/Lit shader), then the default HumanMale race worked.
