### ISSUE TITLE
Please provide a text guide to creating wardrobe assets for UMA 2.5

### ISSUE THREAD

**Issue by larsonmattr** [umasteeringgroup/UMA#198]
I have followed the video tutorials and what document that is available to create my first asset for UMA 2.5. However, after working through this and creating both a slot and wardrobe recipe, and then adding the recipe to an UMADynamicCharacterAvatar, nothing shows up in the scene on run. There are no error messages or helpful feedback to show what is missing from my asset that causes it not to add to the character mesh and become part of the UMA avatar.

I would love to start creating assets for the UMA 2.5 system, but I cannot find a complete and helpful documentation that shows all the required steps going from Blender with a base model -> importing into Unity -> creating the UMA specific components like recipes, slots, overlays as are needed to make a working asset in Unity.

UMA is a very nice system for modular assets and characters, but I think the lack of assets and help to get new users started are a barrier to making this a more popular character system in the Unity Asset Store and with general users.

Please provide a non-video, text-based documentation and tutorial that walks through creating assets new meshes or from taking a piece of the base character asset and scaling up (useful for shirts and pants, etc).

Thanks!

**Comment by larsonmattr** [comment]
As an example, in my case I thought creating a helmet and auto-rigging it to the skeleton in blender would be an easy way to test UMA. Everything seems to be together except the helmet isn't visible when I finally run the scene, while other UMA assets show on the character.

**Comment by Jaimi** [comment]
If you are using 2.5, you should upgrade to 2.7 asap. 
Most likely thing is your blender model is there, but is 1/100th the correct size. 
Another thing to check is that you exported from blender with the correct coordinate system (Y-up, -Z forward). Also make sure your bone weighting is correct. 

Probably best to move the discussion to the forum.

**Comment by larsonmattr** [comment]
Also, what is the address to the forum for UMA?

**Comment by Jaimi** [comment]
There is documentation included with UMA that shows the correct parameters for exporting from Blender. There is older documentation here: https://github.com/huika/UMA/blob/master/UMAProject/Assets/UMA/UMA_Manual.pdf

The forum is:

http://umacommunity.boards.net/

There is also a thread on the unity forums here: 

https://forum.unity.com/threads/uma-unity-multipurpose-avatar-on-the-asset-store.219175/page-153#post-4125379

All help to provide better documentation is more than welcome.

**Comment by Jaimi** [comment]
Added Content Creation PDF to UMA asset folder.

**Comment by ChaimTeco** [comment]
Hey, I'm encountering an issue and wondering if there is a way to fix this-
I'm using UMA to create a customizable character, the character has all its mesh slots in place and several wardrobe recipes, the mesh is being exported from Blender as an FBX. During my workflow I do new FBX exports and overwrite the current FBX file in my unity project, although the FBX itself seems to update correctly to the new export, the UMA character does not seem to receive the updates. For example: some of the meshes have blendshapes exported with them, in blender I add a new blendshape to that mash and re-export the FBX file, going back into unity the exported mesh/FBX shows the new blendshape but the UMA character (UMARenderer) doesn't show the new blendshape, anyone have this issue or know of any solution?

**Comment by Jaimi** [comment]
The UMA character is built from mesh parts called "slots".  To get the updated blendshapes, you have to regenerate the slots.

**Comment by Jaimi** [comment]
You may want to join the discord for a better method of communicating with devs and members:

https://discord.gg/5b39djg

**Comment by ChaimTeco** [comment]
Thank you so much this helped me a lot, I joined the discord as well
