### ISSUE TITLE
Feature request: Add Dna changed callback to UMAData

### ISSUE THREAD

**Issue by DirtyHippy00** [umasteeringgroup/UMA#2]
There is no way right now to know when the DNA has changed since Characterupdated is fired after all of the UmaData dirty flags are already set back to false.  Understanding when DNA has changed is important because when the avatar is changed all state machine behaviours are exited without the exit being called on them.  In some cases you may need to clean up stuff when this occurs.

Adding a CharacterDNAUpdated event to UMAData, and raising it in UpdateUMABody() in UMAGeneratorBuiltIn, before UpdateAvatar(umaData) would be very useful (it needs to be called before this method because this method is where the animator is restored).

**Comment by ecurtz** [comment]
What about FireDNAAppliedEvents()? It looks like they are defined on the slots, which might be troublesome, but if you're adding your state machines with an accessory slot that might be perfect?

**Comment by DirtyHippy00** [comment]
Well this is not really a slot centric pattern.  It is really just "my avatar's, well, avatar, was recreated".  When this happens, even though the animator is not destroyed, it still basically resets the animator (which is why you have to reset all of the parameters).  I need to know when this happens not at the slot level but at the avatar level.

In addition, on my headless environment, I only have avatars with DNA.  No slots / overlays.  This is because slots are not meaningful in headless since they convey presentation layer logic.  I only need the skeleton to be accurate in headless.

**Comment by kenamis** [comment]
I created a pull request for this ecurtz for you to review at your convenience.

**Comment by virror** [comment]
Fixed with: https://github.com/umasteeringgroup/UMA/pull/4
