### ISSUE TITLE
Forward Rendering and Overlays

### ISSUE THREAD

**Issue by droidinteractive** [umasteeringgroup/UMA#21]
When in forward rendering mode, if you reduce dynamic lighting and only rely on point lights or low level lighting, overlays become washed out and lose alpha transparency/blending.  See attached screenshot
![screenshot_17](https://user-images.githubusercontent.com/1417937/28996837-2123ff4c-79bc-11e7-9e30-9ad118f428ea.png)

**Comment by kenamis** [comment]
What version of unity and uma are you using?

**Comment by droidinteractive** [comment]
Unity 5.6.2p4 (DX11)
UMA 2.6

**Comment by kenamis** [comment]
Alright, I'm trying to reproduce it, but in your screenshot I can see it's not only the UMA.  The lantern has the same issue, so I'm thinking it's not an issue specific to UMA.

**Comment by droidinteractive** [comment]
That's because I have Enviro switched over to Deferred Rendering, so the flame/light is on my camera that renders UMA which is set to Forward, so they don't play nice at the moment. I can reproduce in a empty scene with the UMA as well.

**Comment by droidinteractive** [comment]
I just noticed the UMA Crowd demo scene doesn't have this issue if I set the camera to forward rendering and create the same lighting setup. It must be the way I'm generating the Dynamic Avatar and setting up the Slots/Overlays. I'll double check the slot/overlay assignments with the UMA Crowd setup and see if I'm not setting them correctly. Everything works perfect in Deferred Rendering.

**Comment by kenamis** [comment]
Ok. Could you give me the steps to reproduce it or an example project?

On Aug 5, 2017 10:19 AM, "Trenton Shaffer" <notifications@github.com> wrote:

That's because I have Enviro switched over to Deferred Rendering, so the
flame/light is on my camera that renders UMA which is set to Forward, so
they don't play nice at the moment. I can reproduce in a empty scene with
the UMA as well.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/umasteeringgroup/UMA/issues/21#issuecomment-320455875>,
or mute the thread

**Comment by Jaimi** [comment]
It looks like you have different colors on some parts of the model - do
they all share the same shared colors? Are the materials all the same (so
they're on the same atlas)? Is the atlas large enough that it isn't
shrinking some of the textures?

**Comment by Jaimi** [comment]
Also - have you changed the recipe to use the "Swapped head"? It looks like
the eyes are using the swapped set. If so, you should make sure all your
recipes use the swapped head also (otherwise, you can get a mix and match,
with both head meshes and overlays added)

**Comment by droidinteractive** [comment]
Gentlemen, thank you for your assistance. Jaimi got me pointed in the right direction. It was an error on my part. I had the Eyes set to MaleFace instead of MaleHead_Eyes. Working awesome now. I should have checked with the UMA Crowd to begin with. Thank you!
![image](https://user-images.githubusercontent.com/1417937/28997563-97990a40-79cc-11e7-8c6e-ca043f755303.png)

**Comment by droidinteractive** [comment]
![image](https://user-images.githubusercontent.com/1417937/28997658-c86139f2-79ce-11e7-86ff-e07e084505fc.png)

**Comment by kenamis** [comment]
Nice!, Looking good!
