### ISSUE TITLE
Examples and UMA_Examples folders can't be removed without error

### ISSUE THREAD

**Issue by brzGatsu** [umasteeringgroup/UMA#221]
These two folders are quite large (300MB total) and should be removable. However, some scripts in the UMA source seem to reference scripts from these folders which indicates a dependency issue. 

UMAPhysicsSlotEditor -> UMAPhysicsSlotDefinition
DynamicDNAConverterCustomizer -> UMA.CharacterSystem.Examples

**Comment by kenamis** [comment]
This should be possible now in 2.8.1 RC
https://github.com/umasteeringgroup/UMA/releases/tag/v2.8%2C1rc1
