### ISSUE TITLE
Make UMA folder easily movable

### ISSUE THREAD

**Issue by brzGatsu** [umasteeringgroup/UMA#222]
I like to place all external stuff into the Plugins folder to keep my project root clean and get improved compilation times. However, there are a few places in the UMA source that use a hardcoded path. It would be great if you could define the root path in one place to make upgrading easier (or even try to find it dynamically by walking up the folder tree).

**Comment by kenamis** [comment]
This should be possible now in 2.8.1 RC
https://github.com/umasteeringgroup/UMA/releases/tag/v2.8%2C1rc1

**Comment by brzGatsu** [comment]
Hi workes fine except for one thing:

FileUtils::GetInternalDataStoreFolder still works on Application.dataPath/UMA/InternalDataStore
