### ISSUE TITLE
Addressable Asset support

### ISSUE THREAD

**Issue by wirelessdreamer** [umasteeringgroup/UMA#223]
With asset bundles being phased out, the official unity solution will soon be Addressable Assets. having global library items register as addressables is one way to handle this.

**Comment by Jaimi** [comment]
Currently the plan for the next major release is to consolidate the libraries and global library, and back everything with addressables. This will necessitate moving the minimum version of unity to 2018.2 (we'll probably move it to whatever the LTS release of 2018 will be)

**Comment by wirelessdreamer** [comment]
Thanks

**Comment by wirelessdreamer** [comment]
Any rough timeline on that version?

**Comment by Jaimi** [comment]
Not at this time - to do it right makes it a much bigger project than it probably sounds. My guess is somewhere in the next 6 mos.

**Comment by wirelessdreamer** [comment]
I've been getting into addressables lately, and can easily see that.

**Comment by kenamis** [comment]
From my basic understanding asset bundles aren't being phased out.  I
thought they are still there "under the hood", addressables are just a
layer on top. From you looking in to that lately is that not the case?

**Comment by wirelessdreamer** [comment]
After I looked into it a little more I think I took the asset bundle manager being deprecated, as asset bundles being deprecated, so i was off in that.

**Comment by Jaimi** [comment]
FYI - after 2.9 is released in the next few days, development will begin on this feature.

**Comment by wirelessdreamer** [comment]
Feel free to reach out to me for any testing you need, I can make myself available as needed.

**Comment by IvanMurzak** [comment]
Do you have any news?

**Comment by Jaimi** [comment]
The addressable update is currently pending review. As soon as the review is complete, it will be merged into develop, and a 2.10 RC version will be released. Pending no major issues, it will be released to the asset store after a week. It is a major change, and consolidates the libraries and adds automated loading/unloading of items.  This provides significant memory savings.  It has been tested in Android, Windows, WebGL, and should not have a problem on other platforms.

**Comment by IvanMurzak** [comment]
@Jaimi so, how to use it?
I have addressables paths to RaceData, Slot, Overlay, fbx file, texture, UMAMaterial, UMATextRecipe and I have DynamicCharacterAvatar in C#.

**Comment by Jaimi** [comment]
@IvanMurzak  - of course you're free to setup paths/labels and manage the addressables yourself. If you do that, UMA will not know anything about it though - you will have to manage them, and let UMA know they are loaded, etc.   If you let UMA manage the UMA addressables (as outlined in the documentation), then it will label things based on their recipes, and load & reference count items. Note that by default UMA only loads/unloads by label by recipe, and recipes are holders for slots/overlays (& textures).
