### ISSUE TITLE
Animation Override causes Exception / assigns the wrong animator.

### ISSUE THREAD

**Issue by rthompsonj** [umasteeringgroup/UMA#23]
In my project I have a Male animation controller that handles most of the logic and an override controller for females; both have been added to the UMA Library and setup as race animators.  This typically results in an exception similar to:

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.Type,System.Type].get_Item (System.Type key) [0x000a2] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150 
  at UMA.UMAAssetIndexer.AddAssetItem (UMA.AssetItem ai, Boolean SkipBundleCheck) [0x0000e] in /Users/bob/Documents/Unity_Projects/MYUMA/UMA/UMAProject/Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs:487 
``` 

Which is now wrapped in a try/catch via #22 .  The bigger issue here (even with the try/catch) is that the correct animators are NOT applied to the correct race in a built client.  They seem to get assigned correctly when tinkering in the editor.  @Jaimi mentioned on slack that he was aware of this issue and had forgotten about it so I wanted to open an issue as it's preventing me from using override animators in my project.

**Comment by rthompsonj** [comment]
I should also mention that if you add an animation override controller to one of the race animators, then click on the yellow ! in the editor to add it to the library you will encounter the exception.

**Comment by kenamis** [comment]
@rthompsonj , Jaimi and I were looking at this recently and I think he solved it.  He added the AnimatorOverrideController to the GlobalLibrary type list, it's commited in the dev branch now.  The other thing it to make sure the DCA race animator is set to "Dynamically Add  from Global Library".  Do you want to give that a try or do you have a work around now?

**Comment by rthompsonj** [comment]
Thanks for looking into this!  I was just using male animations for everyone as it was less of a headache than trying to bandaid the situation.  Will test out dev and let you know after our public test finishes (in a week or two).

**Comment by kenamis** [comment]
@rthompsonj did you ever get a chance to test this?

**Comment by rthompsonj** [comment]
@kenamis No I am slacking =(
I have a build coming up so let me bump the priority on re-implementing this.  Sorry for dragging my feet on this one.

**Comment by rthompsonj** [comment]
Again sorry for the delay guys!  After testing it appears to be working as expected now.  Thank you for addressing it @kenamis @Jaimi
