### ISSUE TITLE
MeshHiderAsset in HDRP branch

### ISSUE THREAD

**Issue by twobob** [umasteeringgroup/UMA#243]
**Describe the bug**
https://github.com/umasteeringgroup/UMA/blob/feature-HDRP/UMAProject/Assets/UMA/Core/StandardAssets/UMA/Scripts/GeometrySelector.cs#L109  **MeshHiders use wrong shader**

**Environment (please complete the following information):**
 - Unity Version: 2018.3.8f1
 - UMA Version: https://github.com/umasteeringgroup/UMA/commit/dcb95fcb0d5843ffacdfe0384f770a0b8c329caa
 - Platform Build (if not editor):

**To Reproduce**
1. Go to edit a MeshHiderAsset
2. Click on any triangles

**Expected behavior**
They change color

** To Fix **
https://github.com/umasteeringgroup/UMA/blob/feature-HDRP/UMAProject/Assets/UMA/Core/StandardAssets/UMA/Scripts/GeometrySelector.cs#L109
      
>            if (_Materials == null)
>                 {
>                 Shader LitShader = Shader.Find("HDRenderPipeline/Lit");
>                 _Materials = new Material[2];
>                 //Selected
>                 _Materials[1] = new Material(Shader.Find("HDRenderPipeline/Lit"));
>                 _Materials[1].name = "Selected";
>                 
>                 _Materials[1].SetColor("_BaseColor", Color.red);
> 
>                 //UnSelected
>                 _Materials[0] = new Material(Shader.Find("HDRenderPipeline/Lit"));
>                 _Materials[0].name = "UnSelected";
>              
>                 _Materials[0].SetColor("_BaseColor", Color.green);

In the absence of a better solution, that works in the interim

**Comment by Jaimi** [comment]
@twobob  -  the code now looks like this. Does this solve the issue?

```
            if( GraphicsSettings.renderPipelineAsset == null )
            {
                _Shader = Shader.Find("Standard");
            }
            else
            {
                //Expand this to find shaders that work with other SRPs in the future.
                _Shader = Shader.Find("Unlit/Color");
            }

            if (_Materials == null && _Shader != null)
            {
                _Materials = new Material[2];

                //Selected
                _Materials[1] = new Material(_Shader);
                _Materials[1].name = "Selected";
                _Materials[1].color = Color.red;

                //UnSelected
                _Materials[0] = new Material(_Shader);
                _Materials[0].name = "UnSelected";
                _Materials[0].color = Color.gray;

                _sharedMesh.subMeshCount = 2;
                _meshRenderer.sharedMaterials = _Materials;

                _meshRenderer.sharedMaterials[0].hideFlags = HideFlags.HideInInspector;
                _meshRenderer.sharedMaterials[1].hideFlags = HideFlags.HideInInspector;
            }
```

**Comment by twobob** [comment]
looks ok, thanks

**Comment by Jaimi** [comment]
Thanks, I'm just going  back through old issues, making sure everything is working now.
