### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jjackson12172** [umasteeringgroup/UMA#244]
**Describe the bug**

**Environment (please complete the following information):**
 - Unity Version: 2018.3.8.f1
 - UMA Version: 2.8
 - Platform Build (if not editor): Windows10

**To Reproduce**
1. Go to 'UMA on Unity top tool bar'
2. Click on 'UMA'
3. Scroll down to 'Slot Builder'
4. Slot Builder Panel Opens

Applied all mesh and materials as required to create slot. 
Check Marked - Binary, Create Overlay, Add to Library

5. Click "Create Slot Button"
6. UMA Creates (2) Files Only 1.) BinaryAssetWrapper 2.) SkinnedMesh

7. NO Overlay File - Throws Exception:

NullReferenceException: Object reference not set to an instance of an object

UMA.UMAMeshData.FindRoot (UnityEngine.Transform rootBone, UnityEngine.Transform[] bones) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAMeshData.cs:676)

UMA.UMAMeshData.UpdateBones (UnityEngine.Transform rootBone, UnityEngine.Transform[] bones) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAMeshData.cs:618)

UMA.UMAMeshData.RetrieveDataFromUnityMesh (UnityEngine.SkinnedMeshRenderer renderer) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAMeshData.cs:524)

UMA.SlotDataAsset.UpdateMeshData (UnityEngine.SkinnedMeshRenderer meshRenderer, System.String rootBoneName) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/SlotDataAsset.cs:159)

UMA.Editors.UMASlotProcessingUtil.CreateSlotData (System.String slotFolder, System.String assetFolder, System.String assetName, UnityEngine.SkinnedMeshRenderer mesh, UMA.UMAMaterial material, UnityEngine.SkinnedMeshRenderer prefabMesh, System.String rootBone, System.Boolean binarySerialization) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UMASlotProcessingUtil.cs:207)

UMA.Editors.UmaSlotBuilderWindow.CreateSlot_Internal () (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UmaSlotBuilderWindow.cs:217)

UMA.Editors.UmaSlotBuilderWindow.CreateSlot () (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UmaSlotBuilderWindow.cs:158)

UMA.Editors.UmaSlotBuilderWindow.OnGUI () (at Assets/UMA/Core/StandardAssets/UMA/Scripts/Editor/UmaSlotBuilderWindow.cs:94)

**Comment by kenamis** [comment]
What does your skeleton hierarchy look like? Do you have multiple root bones?

**Comment by jjackson12172** [comment]
I'll import a new model from blender and see if the problem happens again.

**Comment by jjackson12172** [comment]
Yup... My bone structure was wrong..My bad!!
