### ISSUE TITLE
Improve assembly definition support

### ISSUE THREAD

**Issue by brzGatsu** [umasteeringgroup/UMA#245]
In order to make it easier for UMA users to add assembly definition files, it would be great if you could combine all Editor folders into one single folder.

**Comment by kenamis** [comment]
Have you tried the 2.8.1 Release Candidate?
https://github.com/umasteeringgroup/UMA/releases/tag/v2.8%2C1rc1

**Comment by brzGatsu** [comment]
Thank's a lot, that slipped my attention!
