### ISSUE TITLE
Serious Rebuild Scale Bug - 100% repro

### ISSUE THREAD

**Issue by Joen-UnLogick** [umasteeringgroup/UMA#250]
**Describe the bug**
When rebuilding the same character over and over as you would with lod the position bone is reduced in size.

**Environment (please complete the following information):**
 - Unity Version: 2018.2.6f1
 - UMA Version: v2.8.1 RC2
 - Platform Build (if not editor): Editor

**To Reproduce**
1. Load 'UMA Core Demo - Texture LOD' Scene
2. Modify the "UMASimpleLOD.cs" script line 142 into "bool changedSlots = true;" this will force a rebuild of the mesh and not just the as well as the textures.
3. Press Play
4. In scene view find a character at a high lod 3+
5. Select the Position Bone, write down the scale
6. Move closer with WASD
7. Observe that when changing LOD the Position Bone changes scale.

**Expected behavior**
It is expected that when rebuilding the same recipe you get the same results.

**Screenshots**

![uma rebuild scale bug_lod3](https://user-images.githubusercontent.com/5825856/54868134-83497b00-4d89-11e9-9a16-3071ea46c573.jpg)
![uma rebuild scale bug_lod2](https://user-images.githubusercontent.com/5825856/54868133-83497b00-4d89-11e9-874f-b51332db764a.jpg)
![uma rebuild scale bug_lod0](https://user-images.githubusercontent.com/5825856/54868132-82b0e480-4d89-11e9-867c-d7f583c6cf67.jpg)

**Additional context**
I originally noticed this problem with the power tools, but was able to reproduce it in UMA Vanilla.

**Comment by Jaimi** [comment]
This was fixed in Release 2.8.1 Thanks!
