### ISSUE TITLE
bone missing

### ISSUE THREAD

**Issue by muyu7** [umasteeringgroup/UMA#254]
**Describe the bug**
missed some bone when generate UMA race asset using my fbx,as if uma ignore some bone by some reason,but i'm not sure!

**Environment (please complete the following information):**
 - Unity Version:2018.2.14
 - UMA Version:2.7.0
 - Platform Build (if not editor):

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kenamis** [comment]
Hi, can you give us some screenshots of your model skeleton before and after in UMA?

**Comment by muyu7** [comment]
> Hi, can you give us some screenshots of your model skeleton before and after in UMA?

thank you for reply!
the following is 3dMax screenshot:
![3dmax](https://user-images.githubusercontent.com/19581517/55848902-3505eb80-5b81-11e9-9ee9-38c4e79a914d.png)

the following is unity screenshot,and the bone named Bip01 Head is missing:
![unity_1](https://user-images.githubusercontent.com/19581517/55848906-3800dc00-5b81-11e9-8bbe-7f7bd0212578.png)
![unity_2](https://user-images.githubusercontent.com/19581517/55848911-39ca9f80-5b81-11e9-9363-54b66b3f6253.png)
![Inkedunity_3_LI](https://user-images.githubusercontent.com/19581517/55848918-3e8f5380-5b81-11e9-89ae-93d2747de2cf.jpg)

**Comment by kenamis** [comment]
Sorry it took me a while to reply.  What does the UMA bone hierachy look like?  Does it generate but missing the head bone? or not generate at all?

You're using UMA 2.7 but on Unity 2018.2? I'm surprised that even worked.

**Comment by muyu7** [comment]
> Sorry it took me a while to reply. What does the UMA bone hierachy look like? Does it generate but missing the head bone? or not generate at all?
> 
> You're using UMA 2.7 but on Unity 2018.2? I'm surprised that even worked.

I finaly soveled that issue，that missing bone was not attached to any vertex，it seemed that UMA thinks that bone is useless and ignore it. is this a bug?
and by the way, should I update my UMA to 2.8.0?

**Comment by Jaimi** [comment]
Not a bug - only bones that are used are brought into the model. We are considering ways to improve this functionality in R3.
