### ISSUE TITLE
Update UMA character before frame update

### ISSUE THREAD

**Issue by ryan-dilili** [umasteeringgroup/UMA#262]
I am trying to generate random characters and save them as images, but due to the real-time nature of the project and asynchronous loading/rendering of meshes and textures, it means that there is an arbitrary wait time to be able to take the picture.

I would like to be able to choose whether I want the character update to occur asynchronously, or before the next frame update.

I've considered using the CharacterUpdated callback, but when there is upwards of 100 characters in the scene it becomes unreasonable to wait for all of them to update, especially considering that they seem to update one by one.

**Comment by Jaimi** [comment]
You can control how many UMAs get generated in a frame with the "iterattions" parameter on the generator. You could conceivably manually "pump" the work through by calling the Work() function on the generator until IsIdle is true as well.

**Comment by ryan-dilili** [comment]
It seems to have worked! quite a funny way to get the work done, thanks!
