### ISSUE TITLE
Instantly update recipes

### ISSUE THREAD

**Issue by Alster** [umasteeringgroup/UMA#267]
Hi!
is there are some way to update character instantly when we just updating recipes?
I mean, when character is already created, and we just applying recipe (for example avatar.LoadFromRecipeString), can I got result immediately, without waiting several frames?

**Comment by Jaimi** [comment]
Yes, in the develop branch. 
On the UMAGenerator Set "Process All Pending" to true.
Call UMAGenerator.Work().

Note: do not do this in one of the UMA events.
