### ISSUE TITLE
No wardrobe loads if loadFilename is set is set but loadFileOnStart is not. 

### ISSUE THREAD

**Issue by FirstGearGames** [umasteeringgroup/UMA#270]
UMA 2.8.1

Quick code fix. More details:

In DynamicCharacterAvatar under Load/Save Options if you have anything in the LoadFilename but LoadFileOnStart is false nothing is loaded by default. Would make more sense if default wardrobe was loaded in this instance.

//fix
        bool BuildUsingComponentSettings
        {
            get
            {
                bool startRecipeEmpty = (loadString == "" && loadFilename == "" && umaRecipe == null);

                if (loadFileOnStart && !startRecipeEmpty)
                    return false;
                else
                    return true;
            }
        }

**Comment by Jaimi** [comment]
Added
