### ISSUE TITLE
BlendShapes not showing in UMARenderer

### ISSUE THREAD

**Issue by hridpath** [umasteeringgroup/UMA#275]
**Describe the bug**
I have exported a Blender model with correction made for UMA conversion. All seems well except that the BlendShapes from Blender do not show.

**Environment (please complete the following information):**
 - Unity Version: 219.2.0f1
 - UMA Version: 2.8.1
 - Platform Build (if not editor): PC stgandalone

**To Reproduce**
1. While running in editor, Go to UMARenderer 
2. Observed no BlendShapes are shown in Skinned Mesh Renderer

.

**Expected behavior**
Expected to see BlendShapes included in Skinned Mesh Renderer inspector

**Screenshots**
![UMA_ISSUE_BlendShapes](https://user-images.githubusercontent.com/15804010/63629856-eb66ec00-c5c9-11e9-9119-5856382c8ddd.png)

**Additional context**

**Comment by kenamis** [comment]
Did you enable "load blendshapes" on the dynamic character avatar component?

**Comment by hridpath** [comment]
Yes. I am following the DAZ to UMA tutorial by Secret Anorak. I have been trying to be very acurate with what I am doing. Just when Part 8 started to assign a BlendShape to a DNA, I realized this issue.

**Comment by hridpath** [comment]
I have found that the FBX import for Unity 2.8 brings in an Armature Deform Modifier for each mesh. Thed modifier cannot be applied because shape keys exist. I can Apply as ShapeKey. 
Blender will attempt to apply any modifier not applied during the export, but if it fails, no Shape Keys are exported. 
This explains why the BlendShapes were not present in Unity.
I am closing this issue.
