### ISSUE TITLE
Compile errors on Unity 2017.2

### ISSUE THREAD

**Issue by mysticfall** [umasteeringgroup/UMA#28]
Upon upgrading Unity from `2017.1` to `2017.2`, _UMA_ fails to load due to the following build time errors:

```
Assets/UMA/Core/Extensions/DynamicCharacterSystem/UMAAssetBundleManager/AssetBundleManager.cs(190,25): error CS0619: `UnityEngine.Application.isWebPlayer' is obsolete: `This property is deprecated and will be removed in a future version of Unity, Webplayer support has been removed since Unity 5.4'
```
```
Assets/UMA/Core/Extensions/DynamicCharacterSystem/UMAAssetBundleManager/UMAAssetBundleManagerSettings.cs(435,13): error CS0117: `UnityEngine.Caching' does not contain a definition for `CleanCache'
```
It seems that removing the offending statement in the former case, and replacing `CleanCache()` with `ClearCache()` in the latter can fix the problem.

**Comment by kenamis** [comment]
@mysticfall I have a pull request with the fixes for this.  It's waiting to be reviewed and merged.  If you don't want to wait, you can just comment out the isWebPlayer code.  For the CleanCache, it's been renamed to ClearCache in 2017.2, so you can just find and replace all those.

**Comment by mysticfall** [comment]
@kenamis I've already done that and it has apparently fixed the problem.

For some reason, the new version crashes like crazy so I had to downgrade back to 2017.1. However, I doubt if it was caused by _UMA_, so I think you can safely close this issue when the PR is merged.

Thanks for the swift response!

**Comment by kenamis** [comment]
Oh haha, duh. I should have read your last sentence again, I was so fixated on the error messages. :)  Thanks for letting us know about the heads up in the first place.

**Comment by kenamis** [comment]
fixes added to dev branch
