### ISSUE TITLE
LWRP(URP) support?

### ISSUE THREAD

**Issue by skelder** [umasteeringgroup/UMA#285]
Hi,

I believe I saw in the update notes that HDRP and LWRP are supported now with 2.9 version update

The release note did say something about changing the assets, but I am quite new to the UMA, so I am not sure where to start.

Is there any guide or do you guys have any plans for doing some guide on how to properly set up the UMA with LWRP?

If not I would really appreciate some hints or pointers as to where to start.

Thank you,

**Comment by kenamis** [comment]
There's no guide yet and I don't recommend it if you aren't already familiar with UMA and how the SRPs work.  
I do have some prebuilt packages for new UMA races set up with LWRP or HDRP.  They may be out of date with changes in the SRP shaders, I'm not sure.
https://github.com/kenamis/UMAHumanLW
https://github.com/kenamis/UMAHumanHD
These will probably be reviewed by the UMA steering committee and made available on the main UMA repository for the next release.

I also have a rough video of making a new race for use with LWRP. https://youtu.be/Pv-szMEZLjc

**Comment by skelder** [comment]
Thank you!

**Comment by Arlorean** [comment]
This may be a bit late but if anyone else comes to this issue the Unity->UMA->SRP menu has an option to do this for you I just found:
![image](https://user-images.githubusercontent.com/1547800/108604088-9749ed00-73a3-11eb-8499-351519416062.png)
