### ISSUE TITLE
Created wardrobe recipe doesn't work

### ISSUE THREAD

**Issue by alex199568** [umasteeringgroup/UMA#286]
**Wardrobe recipe doesn't work**
I created a wardrobe item with slot builder from an exported fbx model. It doesn't affect character in any way. Not sure how to debug it

**Environment**
 - Unity Version: 2019.2.7f2
 - UMA Version: 2.9

**To Reproduce**
1. Import the fbx file into unity
2. Drag `top` from the imported file into slot builder's slot mesh
3. Choose UMA_Defuse_Normal_Specular for UMAMaterial
4. Enable "Create Overlay", "Create Wardrobe Recipe", "Add to Global Library"
5. Hit "Create Slot"
6. Assign textures to the created overlay
7. In Top_Recipe add HumanFemale to compatible races
8. Select Chest in Wardrobe Slot
9. Create Dynamic Character Avatar
10. Add Top_Recipe to wardrobe recipes
11. Run

**Expected behavior**
UMA has a top on it

**Actual behavior**
UMA is naked

**Additional context**
Files:
https://drive.google.com/file/d/1mzjlcPmrVcpgrxTAlHRZBV77GQwrt6QN/view?usp=sharing

**Comment by Jaimi** [comment]
Did you remember to scale it up by 100 in the import settings? If you look
at the renderer in the hierarchy at the materials,  is the overlay added to
the atlas?

**Comment by alex199568** [comment]
When I drag the imported model into the scene the size is fine. I tried to set scale factor in the import settings to 100. Now when I drag it into the scene it's huge, but the UMA still has nothing on it (or around it).

**Comment by Jaimi** [comment]
Please contact me on the discord - https://discordapp.com/invite/sCN8JBy

This is most likely an art or procedural issue that will take some back and
forth.

**Comment by Jaimi** [comment]
probably export parameters. Tested working with Blender 2.8.
