### ISSUE TITLE
Saving UMA character as seperate model

### ISSUE THREAD

**Issue by skelder** [umasteeringgroup/UMA#287]
Hi,

I was wondering if there is a way to save the UMA character that I made created with all the settings into a separate prefab/model that does not rely on the DCS/DCA prefab and system?

So currently when i create settings and save them every time the scene runs the character is built using those data. but i want to be able to see that character and modify/ add animations/ etc during the edit time.

Thank you.

**Comment by nsmith1024** [comment]
Have you tried saving it as a text recipe?

**Comment by Jaimi** [comment]
You can do this with Power Tools on the Asset Store.
