### ISSUE TITLE
Editor Time Tooling

### ISSUE THREAD

**Issue by IsaiahKelly** [umasteeringgroup/UMA#290]
The ability to generate and edit characters outside of play mode can be extremely useful and convenient for a number of situations. The one I'm most interested in at the moment being the creation of timeline sequences with animated characters, which is (as far as I know) impossible to do right now with UMA because everything (including the skeleton) is generated at run time.

So I'd like to help implement the ability to author "pre-baked" UMA content outside of play mode. I am however completely new to this framework and just now learning all the details. So I'd like to get the opinions of more experienced users on this and learn if such a feature has already been attempted and/or discussed and know if there are any major obstacles blocking the implementation of such a feature.

**Comment by HeadClot** [comment]
I would like to echo this. This would be super useful for me. :)

**Comment by Jaimi** [comment]
Coming in 2.11
