### ISSUE TITLE
New UMA Issue

### ISSUE THREAD

**Issue by DrakeDane** [umasteeringgroup/UMA#294]
What is the latest version of UMA? Maybe I need to update again. This started happening recently, for no apparent reason. Although I don't believe I have seen any issues with loading/playing UMA itself, I think this issue might block other normal functions. Example: Think script recompiling wouldn't finish properly, until I cleared up this UMA issue. And the UMA issues is only fixed, by rebooting Unity Editor.

2 Specific symptoms of the problem:

1. When I click on any UMA and check out the Inspector, instead of seeing usual variables, etc for DynamicCharacterAvatar, I see message: "Multi-Object Editing Not Supported". But I am only clicking on a single UMA object. Happens when I click any UMA, once problem appears (which happens daily now).

2. I get a series of error messages in the console. Actually the same 2 error messages listed several times:

a. Instance of DynamicCharacterAvatarEditor couldn't be created. The script class needs to derive from ScriptableObject and be placed in the Assets/Editor folder.

b. Instance of UMADataEditor couldn't be created. The script class needs to derive from ScriptableObject and be placed in the Assets/Editor folder.

Any suggestions? Again, rebooting game seems to fix this. But not clear what is causing it to re-appear. 

Not sure if it is related, but also trying to diagnose Build issue. One of my scenes appears to have some problem. It works fine in the Editor, but get a series of Null Reference Exceptions in Build that cause that scene to not work properly. 

At one point, while testing that issue, I noticed that my main UMA character had lost her assigned DNA. I had to restore her, by using backup save file I keep for all UMA characters. That might just be a coincidence, but no way to be sure. 

I became aware of this UMA issue a few days ago; so no way to know if maybe this is what is causing this other build issue with one of my scenes.

Anyway, let me know, if u need anything more, to try to assist me with this! Otherwise, hoping someone can help me figure this out! Again, maybe I just need to update again! I will check to see what UMA version I have, in case anyone asks about that.

Thanks in advance!

**Comment by Jaimi** [comment]
The latest version is 2.9, available on the Asset Store. The problems you are having look more like library corruption issues, or issues writing to your disk. 
For the null reference exceptions, it may be that you forgot to add "build references" in the global library before building.
