### ISSUE TITLE
About modifying the UMA source code quesstion

### ISSUE THREAD

**Issue by qpuilie** [umasteeringgroup/UMA#299]
I'm a rookie,but i think UMA is quite magic。
we want to define a DNA,and mixture the two textures in different proportions when we change the DNA slider.And i know you mix the texture in the URL"Assets\UMA\Core\StandardAssets\UMA\Scripts\TextureMerge.cs".We want to modify the UMA's code to join the function that mixture the textures.But i dont know what i should do,can you give me some suggestion?

**Comment by qpuilie** [comment]
i want to change the people skin(young to old) through move the slider.

**Comment by Jaimi** [comment]
Questions are probably better addressed on the slack or discord. But what you need is "color DNA". this will allow you to merge two overlays (including normal maps) with DNA.  For an example, see the "ElfOrAlien" DNA which does just that (and changes skin color also).
