### ISSUE TITLE
Small bug still with updating slots/textures without DNA

### ISSUE THREAD

**Issue by DirtyHippy00** [umasteeringgroup/UMA#3]
Recently we fixed (ecurtz/kenamis) some issues preventing updating slots/textures without DNA (it would reset the DNA before the fixes).  However, I have found that the fix to EnsureBone (which was to comment out "res.umaTransform.Assign(umaTransform);" didn't work:

		/// <summary>
		/// Ensures the bone exists in the skeleton.
		/// </summary>
		/// <param name="umaTransform">UMA transform.</param>
		public virtual void EnsureBone(UMATransform umaTransform)
		{
			BoneData res;
			if (boneHashData.TryGetValue(umaTransform.hash, out res))
			{
				res.accessedFrame = -1;
			//	res.umaTransform.Assign(umaTransform);
			}
			else
			{
				AddBone(umaTransform);
			}
		}

Does not fix the issue unless the line "res.accessedFrame = -1;" is also commented out or else it gets picked up in EnsureBoneHierarchy and gets reset (I think - you can also just comment out EnsureBoneHierarchy while leaving the line above commented in, and it works too.  I'm not sure what is going on with tracking the frames bones are accessed.

		private void CreateTransforms(UMASkeleton skeleton)
		{
			for(int i = 0; i < umaBoneCount; i++ )
			{
				skeleton.EnsureBone(umaBones[i]);
			}
			skeleton.EnsureBoneHierarchy();
		}

**Comment by ecurtz** [comment]
I honestly have very little recollection about what the accessedFrame field is trying to solve. I vaguely recall complaining about it in the past and receiving some sort of explanation, it might be obsolete at this point, or perhaps PowerTools is using it in some way?

I didn't think that EnsureBoneHierarchy() would be an issue because it isn't changing the bone data like the other one was it's just resetting, but I think that should be to the existing current state.

**Comment by DirtyHippy00** [comment]
I agree - this certainly seems like sketchy behaviour, but since that logic is used in many places I suspect it is actually there for a reason.  I am guessing by not executing this logic we will see some side effects at some point - but I have not noticed any myself with a decent bit of testing now (with both full updates and just slot/overlays).

**Comment by Jaimi** [comment]
Is this still an issue, or can this item be closed?

**Comment by DirtyHippy00** [comment]
This is still an issue.  The only way it behaves as expected is if "res.accessedFrame = -1;" is commented out in EnsureBone.  I upgraded to the newest UMA not super long ago, and I had to make this change manually (I had an internal reminder comment for it), in order for this to work correctly.

**Comment by Jaimi** [comment]
Removed and tested with ragdoll, additional boned slots, changing race, etc.
