### ISSUE TITLE
Uma layout in inspector looks corrupted

### ISSUE THREAD

**Issue by jammygitgames** [umasteeringgroup/UMA#300]
Hi,

Firstly, I'd like to say how amazing UMA is. You can create a wide range of fantastic characters in a short space of time which is brilliant for an indie developer like me. I'm new to UMA and I'm working my way through the Secret Anorak tutorials which again are amazing, very easy to follow and cover everything you need to know. 

As I'm new to this, I may be doing something wrong, but I'm having issues with the layout of some of the UMA content in Unity (particularly assets and recipes). I attach a few screenshots to show you what I mean. The inspector view of the characters is fine. 

**Environment (please complete the following information):**
 - Unity Version: 2019.3.0a3
 - UMA Version: 2.9 (downloaded a few days ago)
 - Platform Build (if not editor): I'm just using the normal Unity Editor. 

![UMA asset](https://user-images.githubusercontent.com/60824792/74090496-ddd3ee80-4aa3-11ea-9003-9659243fc633.JPG)

![UMA recipe](https://user-images.githubusercontent.com/60824792/74090499-e2000c00-4aa3-11ea-87af-2bc7d4c8196a.JPG)

**Comment by Jaimi** [comment]
Tested working in release version of 2019.3

![um2019 3](https://user-images.githubusercontent.com/11434720/74094585-54bfb600-4aa9-11ea-8193-af59113c843e.png)

**Comment by jammygitgames** [comment]
Hi Jaimi, many thanks for that. I have upgraded to the latest version of Unity and it works now.
