### ISSUE TITLE
[UMA 2.9] Assigning recipe to the Dynamic Character Avatar doesn't load the recipe

### ISSUE THREAD

**Issue by VergilUa** [umasteeringgroup/UMA#303]
Assigning a pre-designed dynamic recipe to the Dynamic Character Avatar doesn't load the recipe, instead it loads the default race w/o any changes.

 - Unity Version: 2019.3.1f1
 - UMA Version: 2.9 (Package manager version downloaded from Asset Store access)

**To Reproduce**
1. Assign custom made UMA recipe to the Dynamic Character Avatar field.
2. Enter playmode.
3. Observe that default race has been loaded instead of the recipe

**Expected behavior**
Custom recipe should be loaded instead.

**Additional context**
This problem is caused by the BuildUsingComponentSettings property in the DynamicCharacterAvatar.

Instead of 
```
        bool BuildUsingComponentSettings
        {
            get
            {
				bool startRecipeEmpty = (loadString == "" && loadFilename == "" && umaRecipe == null);

				if (loadFileOnStart && !startRecipeEmpty)
					return false;
				else
					return true;
			}
        }
```

That should be:
```
        bool BuildUsingComponentSettings
        {
            get
            {
				bool startRecipeEmpty = (loadString == "" && loadFilename == "" && umaRecipe == null);

				if (loadFileOnStart || !startRecipeEmpty) // OR instead of AND here
					return false;
				else
					return true;
			}
        }
```

Changing that line fixes the issue.

**Comment by Jaimi** [comment]
Pushed to latest release. Thanks.
