### ISSUE TITLE
The normal problem caused by the DNA change

### ISSUE THREAD

**Issue by obuffer** [umasteeringgroup/UMA#304]
I used UMA DNA to adjust the bone, because the position of the vertex has changed, so it affects the triangles, the normal of the triangles should be changed, but it is not changed now.No matter how much I change the DNA, the lighting calculation stays the same, right

**Comment by kenamis** [comment]
That is by design and to be expected.  You can use normal maps you blend towards or manually call recalculate normals, but that is costly.
