### ISSUE TITLE
[UMA 2.10] Changing a recipe sometimes causes a strange pixelization on characters

### ISSUE THREAD

**Issue by pedropla** [umasteeringgroup/UMA#308]
Using UMA 2.10 on MacOS with Unity 2019.3.12f1.

When changing the recipe of a character a strange pixelization happens sometimes. Sometimes it goes away when a new recipe is loaded sometimes more pixelization occurs.

This happens in demo scenes as well as when changing in code in my own scenes. Not sure if it's a known bug. See screenshot below.

It might be a memory leak of some sort because when I tried changing back and forth between wardrobe items in code repeatedly (to see if there was a pattern of when this happened and when it didn't) I managed to crash unity itself.

<img width="739" alt="Screen Shot 2020-05-05 at 5 57 28 PM" src="https://user-images.githubusercontent.com/13673481/81054808-1136e580-8efa-11ea-904a-a76e32b977f9.png">

**Comment by kenamis** [comment]
Did you have this issue on previous versions of UMA?  Is this built-in rendering pipeline or one of the SRPs?  Are your video drivers up to date?

**Comment by pedropla** [comment]
This is with built-in rendering. All video drivers (for MacOS) are up to date and Unity/UMA are the latest version. I haven't tried it on previous versions of UMA or Unity as I've just started testing UMA recently.

Is there any way I can provide further information which might help with debugging the issue? I'm not at all familiar with the UMA platform so I'm not sure where to look.

Thanks

**Comment by pedropla** [comment]
Just to update, I've tried this with URP and I'm still getting the same issues.

**Comment by kenamis** [comment]
Try this, search for the "TextureMerge" scriptableObject and replace the
"Normal Shader" with "AtlasShaderNormal32".
[image: image.png]

**Comment by pedropla** [comment]
I've given it a try and I'm still seeing that pixelation. 

To see if it could be an issue with all the UMA shaders I even replaced the Normal Shader with the URP/Lit and Unlit shaders and the pixelation was still occurring after certain recipe changes.

So perhaps it isn't a shader issue but something to do with regenerating the mesh after adding/removing clothing?

**Comment by kenamis** [comment]
If you inspect the textures that are built and on the renderer at runtime,
do you see those artifacts?

**Comment by pedropla** [comment]
Ok, that seems to have narrowed it down. It seems to be something in the generation of the Metallic Map.

When I remove the Metallic Map it removes those artefacts. See screenshots below.

<img width="1148"  src="https://user-images.githubusercontent.com/13673481/81956270-b0b45080-963d-11ea-9cef-0d2e953f84e9.png">

<img width="1144" src="https://user-images.githubusercontent.com/13673481/81956306-b7db5e80-963d-11ea-8615-e29ce322753d.png">

**Comment by kenamis** [comment]
if you examine the generated metallic textures do they have those square artifacts?

**Comment by pedropla** [comment]
It's hard for me to see as the preview is very small (screenshot attached). 

<img width="399" src="https://user-images.githubusercontent.com/13673481/82000164-0d3d5d00-968a-11ea-8b75-7e8e20c2c31a.png">

I'm trying to export the bitmaps but the documentation I find online to do that is very old and doesn't work in the latest unity. Is there a way I can export the full generated texture to see it?

**Comment by Jaimi** [comment]
@pedropla  - What model mac do you have, and what type of graphics?
I had a problem very similar to this on my imac (2013) that turned out to be a driver issue.
I don't know the state of Mac Development right now (my imac fusion drive croaked), but can you switch between Metal and OpenGL to see if it's still a problem?

**Comment by pedropla** [comment]
@Jaimi I'm using the MacBook Pro 13-inch, 2016. Graphics card: Intel Iris Graphics 550. 

I've tried switching as you suggest and yes, the problem seems to be with the Metal graphic system. When I switch to OpenGL it works. However, it's not feasible to switch permanently as Metal is now the default graphic system and much less is supported in OpenGL than Metal.

I also haven't experienced any similar issues with any other Unity Assets with the Metal graphic system.

**Comment by Jaimi** [comment]
@pedropla  - with that system, it shares RAM with the machine, so you may be low on what it considers "video memory".  As a test, if you can set the generator to scale to 4, and lower the Atlas size to 1024, do you still get the issue?

**Comment by pedropla** [comment]
@Jaimi Sorry I'm pretty new to UMA and I'm not sure exactly how to do this. I didn't see these options in the UMA menu or in the UMA Character object.

What I did see in the UMA DCA script options on the character was the following Atlas resolution scale. When I reduced it to about half of the standard 1, I no longer saw this issue occurring. Screenshot below.

<img width="370"  src="https://user-images.githubusercontent.com/13673481/82022151-c027ae00-96be-11ea-9ee3-cb557c0bce12.png">

Does that mean that this issue is due to too little video card memory? If so, how will that affect a game that's used on for example a mobile device that also has very little video memory?

Is it considered a bug or just something to be aware of? If it's something to be aware of, what is the correct way to detect and adapt Atlas resolution accordingly?

Thanks!

**Comment by pedropla** [comment]
I spoke to soon.. Even with the Atlas Resolution Scale reduced it still happens. Just less often.

**Comment by pedropla** [comment]
@Jaimi I found the settings you mentioned and I had to lower the Atlas size to 512 before the problem stopped showing up frequently. 

<img width="385" src="https://user-images.githubusercontent.com/13673481/82177969-86001b80-990d-11ea-8ba6-ca54e141f8c9.png">

**Comment by Jaimi** [comment]
I think this is a problem with Unity and the driver.  I'm sorry, but not much we can do with this. You can use the option to "Convert Render Texture" to move all of the textures to system memory. Warning: it is slower. Or you can switch to OpenGL.  We have a feature coming in 2.11 to delay moving the textures to system ram, which should help significantly with the stalling.

**Comment by pedropla** [comment]
Thanks for having looked into it!
