### ISSUE TITLE
[UMA 2.10] Addressables and asmdef

### ISSUE THREAD

**Issue by brzGatsu** [umasteeringgroup/UMA#310]
When enabling the addressables support in Unity 2019.3 AND using asmdef files, I am required to add a Unity.Addressables.**Editor** reference to UMA_Core.asmdef due to UMAAssetIndexer.cs. This should be fixed.

Also I cannot get the UMA_Examples.asmdef to compile, even though I added Unity.ResourceManager and Unity.Addressables references to the asmdef.

- No overload for method 'DownloadDependenciesAsync' takes 3 arguments (Preloader.cs)
- 'IResourceLocator' does not contain a definition for 'LocatorId' and no accessible extension method 'LocatorId' accepting a first argument of type 'IResourceLocator' could be found (are you missing a using directive or an assembly reference?) (SampleCode.cs)

**Comment by Jaimi** [comment]
You must use the latest version of Addressables (1.8.4 as I write this).  It's available in the package manager, even though Unity makes it hard to find on 2019.3.
Asmdef is fixed in the current pull request waiting for merging.
