### ISSUE TITLE
Weird combined mesh using Unity 2019.3.11.f1

### ISSUE THREAD

**Issue by SilverDDX** [umasteeringgroup/UMA#311]
Hi, thank you for this asset.
I'm currently trying to use it in my project, however I encounter weird mesh results when working with the female avatar. The breasts of the avatar appear very weird.
I tried to reimport the package, but even in a blank project, I'm getting this distorded female avatar.

I also tried to use an older version of unity (2018 last LTS version), and I'm not having this issue.
Have you any idea for solving this, I would prefer to keep Unity 2019 ?

Thank you.

![image](https://user-images.githubusercontent.com/43643372/82194973-eedc9900-98f7-11ea-9f4f-a7e4ea242eb1.png)

**Comment by Jaimi** [comment]
You need to set your quality settings to 4 bone weights.

**Comment by dstoffels** [comment]
I've come across the same issue on 2019.4, however the quality settings didn't solve it. Has anyone else encountered this issue since making the switch from Unity 2018?

**Comment by Jaimi** [comment]
This is 100% quality settings. Be sure you update ALL the quality settings.
