### ISSUE TITLE
Maximum vertex count

### ISSUE THREAD

**Issue by rayuthebest** [umasteeringgroup/UMA#313]
Hello,

I am trying to use UMA 2 library to import high poly 3D models on my game. I am currently using v2.9 (although I have also tested v2.10 and problem persist)

When I tried the first time to import a helmet for my high poly 3D model on UMA, library reports me the next error:

_Could not claim shared submesh buffer of size: 277572_

Tracing this error, I found that it was related with the MAX_VERTEX_COUNT constant defined at UMA/Core/StandardAssets/UMA/Scripts/UMAMeshData.cs file.

Looking on changelog of v2.10, I see that this constant has been increased to allow importing high poly models. I download this version. but problem persist (it seems that although the buffer sizes have been increased, they are not enough for my game)

Due to this fact, I have increased the MAX_VERTEX_COUNT constant to 10.000.000 (on version 2.9 and v2.10) and the error reported by the app disapeared but a new issue appears.

- If I only import a high poly helmet, the model is correctly generated.

![Helmet](https://user-images.githubusercontent.com/13403324/83347401-277f6800-a325-11ea-80b1-f819df6e7cfa.JPG)

- If I remove the helmet and select the shoulders, the model is also correctly generated.

![Shoulders](https://user-images.githubusercontent.com/13403324/83347373-ee46f800-a324-11ea-8abd-845176bec306.JPG)

- But if on the same model I import both wardrobes, the whole mesh become a mess.

![Helmet_Shoulders](https://user-images.githubusercontent.com/13403324/83347389-0e76b700-a325-11ea-84b1-56ac8ee37f5f.JPG)

It seems that there is something related with the vertex count on the model, but as no error appears, I cannot trace this issue easily.

Can you give me some support? Tell me if I can help you on anything to solve this issue.

Thanks in advance

**Comment by rayuthebest** [comment]
Hello again,

After investigating a little on this issue, I found that it was related with the mesh indexFormat field of the SkinnedMeshRenderer at UMAData.cs. This field is set on UInt16, so the number of vertex and triangles is limited in order to provide greater performances.

I have solved my issue on the method SetRenderers at UMAData.cs (I do not know if this is the best solution), adding the next modification:

`
public void SetRenderers(SkinnedMeshRenderer[] renderers)
{
   this.renderers = renderers;
   foreach(SkinnedMeshRenderer render in renderers)
   {
      render.sharedMesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
   }
}
`

**Comment by KABBOUCHI** [comment]
Did you try this from the doc?
> Added support for 32 bit index buffers (large meshes). To enable, add UMA_32BITBUFFERS to the player defines. This is experimental at this time.

**Comment by Jaimi** [comment]
There is now a UMA preference item to enable 32 bit meshes. Closing.
