### ISSUE TITLE
AddressableInfo and AddressableUtility does not exists in the current context

### ISSUE THREAD

**Issue by wandura** [umasteeringgroup/UMA#315]
**Describe the bug**
Errors on updating to UMA v2.10.1.RC1:
```
Assets\UMA\Core\Scripts\UMAAssetIndexer.cs(1264,5): error CS0246: The type or namespace name 'AddressableInfo' could not be found (are you missing a using directive or an assembly reference?)

Assets\UMA\Core\Scripts\UMAAssetIndexer.cs(1264,29): error CS0103: The name 'AddressableUtility' does not exist in the current context

Assets\UMA\Core\Scripts\UMAAssetIndexer.cs(1719,17): error CS0246: The type or namespace name 'AddressableInfo' could not be found (are you missing a using directive or an assembly reference?)

Assets\UMA\Core\Scripts\UMAAssetIndexer.cs(1719,41): error CS0103: The name 'AddressableUtility' does not exist in the current context
```

**Environment**
 - Unity Version: 2019.4.1f1
 - UMA Version: 2.10.1.RC1

**Comment by Jaimi** [comment]
Were you were previously using the asmdef? If so, there are new ones for this release, youll need to remove the old ones, and use the menu item to rename the new ones.

**Comment by wandura** [comment]
No I don't have any asmdef in my project. Is one needed for UMA to work?

**Comment by wandura** [comment]
The errors disappear as soon as I use the asmdef for UMA.

**Comment by Jaimi** [comment]
hmm - it should work either way. I'll try to duplicate this.

**Comment by Jaimi** [comment]
Followup: I am able to duplicate this if I turn OFF asmdef, and I turn ON addressables.  I'm currently considering shipping with asmdef files on by default, since I can't really figure a way to make it work otherwise (without some hackish #if in the code, and duplicating the classes!)

**Comment by Jaimi** [comment]
This is now fixed and will be in the next update.
