### ISSUE TITLE
Slot Builder doesn't accept any mesh

### ISSUE THREAD

**Issue by danieloquelis** [umasteeringgroup/UMA#317]
I'm trying to create my custom slot using the slot builder but when I try to add a "Slot Mesh" it doesn't allow me to insert any model I have. I've tried with different formats: FBX, files directly from blender, OBJ, etc. I don't know if there's any special format to use for importing and use it into Slot Builder.

 - Unity Version: 2019.3.15f1
 - UMA Version: 2.10

1. Go to 'UMA/Slot Builder'
2. Try to drag any model into "Slot Mesh"

**Comment by kenamis** [comment]
You probably either don't have a skinned mesh renderer on your imported
object (you object needs skinning data), or you're not selecting your
sub-object with the skinned mesh renderer on it.  The skinned mesh renderer
is the object that the slot builder is expecting.

**Comment by danieloquelis** [comment]
Thanks for the answer,

I'm pretty sure I've selected the sub-object but I'm not sure if It has the skinned mesh renderer.

I'll try to figure that out.

**Comment by Jaimi** [comment]
Tested working in 2.11

**Comment by k1i2y2o5ka** [comment]
What does it mean to select a sub-object that contains a skin mesh renderer?
I am in trouble because I have a similar problem.
If you do not mind, please teach me.

**Comment by Jaimi** [comment]
Sometimes Unity hides the Skinned Mesh Renderer in a subobject that you can't get to.  When that happens, you just need to use the "drag and drop" -- drag the FBX into the area of the slot builder for automated slot building.

**Comment by cnguyen11235** [comment]
i ran into a same issue, it's because your mesh doesn't have bones attached to it, hope this help devs in future!
