### ISSUE TITLE
Support for "enter play mode settings"

### ISSUE THREAD

**Issue by ChemsoDev** [umasteeringgroup/UMA#320]
**Is your feature request related to a problem? Please describe.**
disabling domain reload prevent textures from loading at runtime
Example:
Domain reloads disabled:
![image](https://user-images.githubusercontent.com/41765106/87884284-68325e00-ca05-11ea-9032-e5edcae514b7.png)
![image](https://user-images.githubusercontent.com/41765106/87884287-72545c80-ca05-11ea-87b8-68d94052c167.png)
Domain Reloads Enabled (or option disabled):
![image](https://user-images.githubusercontent.com/41765106/87884325-cfe8a900-ca05-11ea-8cda-7749fed79c87.png)
![image](https://user-images.githubusercontent.com/41765106/87884328-da0aa780-ca05-11ea-9622-a3fcc04fad2f.png)
![image](https://user-images.githubusercontent.com/41765106/87884339-e2fb7900-ca05-11ea-8914-b7e5391104e3.png)

**Describe the solution you'd like**
@kenamis 's reply (Discord) :

> _"@Chakib disabling domain reload would cause problems for UMA (as you see) because UMA uses static Lists to reduce garbage.  A pass would have to be made to make that work with the new ability to disabled domain reload."_

**Describe alternatives you've considered**
//A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
//Add any other context or screenshots about the feature request here.

**Comment by mat27** [comment]
Bump

Domain Reload saves a lot of time in big projects. I feel like this is essential. I was having the same issue until i found this.

**Comment by Jaimi** [comment]
Is this still an issue in 2.11.6? I can't seem to duplicate it.

**Comment by Jaimi** [comment]
Since I cannot duplicate the issue, I am closing this. If you can duplicate in the current version, please re-open or create a new issue.
