### ISSUE TITLE
Starting guide not working in Unity 2019.4.7f1

### ISSUE THREAD

**Issue by jacquesbrits1** [umasteeringgroup/UMA#327]
I am new to Unity and UMA

After looking at the "getting started" guide I downloaded and imported the UMA package 

I then dragged the UMA_DCS over and as soon as I hit play I got errors that it could not find the animator.

EDIT: Wiki and online guides are outdated and does not correspond to the PDF Documentation. After reading the documentation I was able to get it to work. 

 - Unity Version: 2019.4.7f1
 - UMA Version: 2.10.1
 - Rendering Pipeline: Standard
 - Platform Build (if not editor):

1. Downloaded and imported the UMA package
2. In a new scene drag the UMA_DCS in the scene
3. Create new game object
4. Add DynamicCharecterAvatar Script
3. Press play
4. See attached screenshots

![2020-08-13 00_06_58-Window](https://user-images.githubusercontent.com/43321214/90073267-30af8c80-dcf9-11ea-8459-11566f65a71f.png)
![2020-08-13 00_08_27-Window](https://user-images.githubusercontent.com/43321214/90073271-31482300-dcf9-11ea-8b83-bfc7297c57a2.png)

**Comment by Jaimi** [comment]
Thanks, the getting started needs to be updated. It should now say "drag the UMA_GLIB" object into the scene. I'll go through the steps, and make sure everything is up to date.

**Comment by Jaimi** [comment]
Updated in 2.11 with new workflow (edit time UMA, etc)
