### ISSUE TITLE
Avatar mesh not created in the scene

### ISSUE THREAD

**Issue by tomaszzackiewicz** [umasteeringgroup/UMA#33]
I have downloaded the recent UMA 2 from the Asset Store and all worked great. As soon as I installed Unity 2017.1p5, I get the error:

SkinnedMeshRenderer: Trying to set a mesh ("") that is unfit for use with SkinnedMeshRenderer. Most likely it doesn't have Skin information and/or is only assigned to the renderer during runtime, in which case Unity isn't aware of its use with SkinnedMeshRenderer. Mark the mesh as Readable or assign it to the renderer in the Editor before building.
UnityEngine.SkinnedMeshRenderer:set_sharedMesh(Mesh)
UMA.UMADefaultMeshCombiner:MakeRenderer(Int32, Transform) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMADefaultMeshCombiner.cs:96)
UMA.UMADefaultMeshCombiner:EnsureUMADataSetup(UMAData) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMADefaultMeshCombiner.cs:44)
UMA.UMADefaultMeshCombiner:UpdateUMAMesh(Boolean, UMAData, Int32) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMADefaultMeshCombiner.cs:117)
UMA.UMAGeneratorBuiltin:UpdateUMAMesh(Boolean) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:282)
UMA.UMAGeneratorBuiltin:HandleDirtyUpdate(UMAData) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:226)
UMA.UMAGeneratorBuiltin:OnDirtyUpdate() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:265)
UMA.UMAGeneratorBuiltin:Work() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:132)
UMA.UMAGeneratorBuiltin:Update() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:97)

**Comment by xypherorion** [comment]
Confirmed that this is not caused in 2017.1p4.
Occurs in 2017.1p5 (tested) and 2017.2 b8 (tested)
Downgrading back to 2017.1p4 works fine as a workaround.

**Comment by tomaszzackiewicz** [comment]
Great! I will wait for a fix. Hope it will come soon.

Thanks!

**Comment by checkpointng** [comment]
Does anyone know if this still applies to 2017.1 ?

**Comment by kenamis** [comment]
I downloaded the latest non beta version a couple days ago. I think it was
2017 1.1. And it was working, no issue.

**Comment by tomaszzackiewicz** [comment]
2017.1 all versions with patches including teh recent one - all seems OK.

**Comment by kenamis** [comment]
Thanks for checking.
