### ISSUE TITLE
placeholder doesn't appear

### ISSUE THREAD

**Issue by gekidoslair** [umasteeringgroup/UMA#330]
**Describe the bug**

New scene with 2 prefabs:

UMA_GLIB or UMA_DCS (same results with either)
+
UMADynamicCharacterAvatar 

The placeholder 'ghost' object doesn't appear in the scene. 

**Environment (please complete the following information):**
 - Unity Version:  2019.4.11f1
 - UMA Version:  2.10.1
 - Rendering Pipeline:  built in 
 - Platform Build (if not editor): editor

**To Reproduce**
1. create a new scene
2. add UMA_GLIB and UMADynamicCharacterAvatar prefabs into scene
3. notice there is no placeholder shown

Checking / unchecking the placeholder option on UMADynamicCharacterAvatar and/or switching races do not fix this either.

**Expected behavior**
That the 'ghost' placeholder mesh should appear as described in the documentation / examples videos

**Comment by Jaimi** [comment]
The placeholder is a gizmo - can you verify that the gizmos are enabled, and the DynamicCharacterAvatar is not collapsed in the inspector?

**Comment by Jaimi** [comment]
Placeholder is now supplanted by edit-time UMA generation.
