### ISSUE TITLE
New UMA Avatar floating in air

### ISSUE THREAD

**Issue by NikoMix** [umasteeringgroup/UMA#331]
**Describe the bug**
A newly added Avatar seams to be floating in the air with a plain new project and even terrain. I'm not sure if I missed something/configured something wrong or if this is about the collider

**Environment (please complete the following information):**
 - Unity Version: 2019.4.12f1
 - UMA Version: 2.10
 - Rendering Pipeline URP
 - Platform Build (if not editor): Editor

**To Reproduce**
1. Add new UMA Dynamic Character Avatar (HumanMaleDCS)
2.Add UMA_DCS Prefab 
3. Run Editor

**Expected behavior**
The Model should be properly grounded to the terrain and not floating ~5cm in the air

![Runtime](https://user-images.githubusercontent.com/809210/96413711-5327bf80-11ec-11eb-8d9c-055f182f548c.PNG)
![Editor](https://user-images.githubusercontent.com/809210/96413728-58850a00-11ec-11eb-8044-cae3adf7e68d.PNG)

**Comment by Jaimi** [comment]
Unable to duplicate issue in UMA 2.11
