### ISSUE TITLE
"cannot find generator" error even after installing all the UMA assets and cannot customize the character's body and lip phenomes and emotions

### ISSUE THREAD

**Issue by anmol1905** [umasteeringgroup/UMA#342]
**Describe the bug**
"**cannot find generator**" error even after installing all the UMA assets. Also **editor time generation** not working
 when i am going in Dynamic Character Avatar and selecting the active race one error pops up saying "cannot find generator"
after some time i figured out that in advanced options the uma generator slot was empty so i selected the default uma generator
but still the error pops up and also i am not able to **customize the body of the character**, when i am sliding the bar nothing is changing

**Environment (please complete the following information):**
 - Unity Version: Unity 2021.1.0b1 (64-bit)
 - UMA Version: Version 2.11.4 - January 05, 2021
 - Rendering Pipeline:
 - Platform Build (if not editor):

**To Reproduce**
1. Create new scene
2. install uma2 asset
3. (in my case install lipsync pro and in extensions install uma2 blend system)
4. Create empty object
5. search UMA_DCS in assets and drag it to heirarchy
6. in empty object click script and search dynamic character avatar
7. in active race select anything to see the error popup (i tried selecting male high poly and few others and it shows up only once at the start and while chaning the dress and hairs of the character)
8. try changing the predefined dna that to is not working

**Expected behavior**
the error pop up should not show and the character should be able to customize ( like the height and everything)

**Additional context**
It used to work perfectly fine few months back

**Comment by Jaimi** [comment]
The new functionality needs the "UMA_GLIB" in the scene. I moved the older UMA_DCS to the deprecated folder. I should probably just make this a clone of UMA_GLIB. If you see the same thing with the UMA_GLIB in the scene, please let me know.

**Comment by Jaimi** [comment]
New version will now auto-gen a UMA_GLIB if one does not exist.

**Comment by anmol1905** [comment]
Thank you! Now it is working. I am sorry for the late reply😊

**Comment by JorgeCerda1401** [comment]
Hi, I am having this same issue. I have unity 6.1 and I am using 2.14f6 version of UMA. I couldn't find any other post of this problem.

<img width="2559" height="1289" alt="Image" src="https://github.com/user-attachments/assets/444dc450-81c7-4df4-8379-f29b08e52e57" />
