### ISSUE TITLE
UMAAssetIndexer - addressable parameter issue

### ISSUE THREAD

**Issue by veriok** [umasteeringgroup/UMA#344]
Hello,
I tried to look up the problem, and found some discussion on unity forum about it, but the proposed solution (update of addressables package) did not help.

**Description**:
When using **Unity 2019.4.12f1**, along with **Addressables 1.8.5** (latest showing in package manager, verified for 2019.4) and latest **UMA 2.11.5** downloaded via Unity AssetStore, in a brand new unity project, after enabling addressables in Global Library UMAAssetIndexer is throwing error:
`Assets\UMA\Core\Scripts\UMAAssetIndexer.cs(1109,35): error CS1501: No overload for method 'LoadAssetsAsync' takes 4 arguments`

**Steps to reproduce**:
* Download Unity 2019.4.12.f1
* Use package manager to install Addressables 1.8.5
* Download UMA via asset store
* _(Optional) resolve C# level compiler errors - may only happens for me as im using Intelij Rider as my IDE, and few places requires C#7.0 or 7.1 features enabled_, it goes away afterwards though
* Enable addressables in UMA Global Library

**Expected results**: It will be working
**Current result**: Compilation issue mentioned above, no easy solution to tweak the code as we're operating on list of strings (labels) and LoadAssetsAsync depends on objects, and I did not work so far with async code in c#.

**Comment by Jaimi** [comment]
UMA requires a later version of Addressables in 2.11.5.  The latest production version for 2019.4 is 1.16.15.  Please use the Package Manager to download that version and install.
