### ISSUE TITLE
Import UMA fbx on Maya

### ISSUE THREAD

**Issue by boehm-e** [umasteeringgroup/UMA#353]
Hi, 
does anyone have successfully imported and modified a UMA character fbx, or created content for UMA in Maya ?
Because when I open the provided FBXs in maya 2019, a lot of things are wrong. Is there any tutorial, or the only possible way is blender ? 
Thank you

**Comment by Jaimi** [comment]
Maya has been popular with some UMA users. I recommend to use the discord for discussion about UMA and different modelling tools.

https://discord.gg/sCN8JBy
