### ISSUE TITLE
Some recipes I am purchasing arent installing correctly into the library

### ISSUE THREAD

**Issue by peachpieproductions** [umasteeringgroup/UMA#354]
I have bought a couple clothing packs (that are not that old) and they will have issues and errors when trying to use them, even after adding the recipes to the global library. 

Is there an easy way to update recipes to whatever the latest standard is for UMA? 

 - Unity Version: 2019.4.18f1
 - UMA Version: 2.11.5
 - Rendering Pipeline: Built in

**Comment by Jaimi** [comment]
The most common reason for this is Unity losing references during the package import.  If that's not the problem, you can make sure that everything in the recipe is in the library, by running the "Rebuild from project" option in the File Menu of the Global LIbrary.

**Comment by peachpieproductions** [comment]
Okay I will try that thank you!
