### ISSUE TITLE
Huge Size

### ISSUE THREAD

**Issue by mixxit** [umasteeringgroup/UMA#358]
**Describe the solution you'd like**
Does this have to be 500mb? Can you add a minimal install to the pipeline?

Thanks!

**Comment by Jaimi** [comment]
It is huge, I know.  If you're not interested in the examples, you can unselect that folder when importing.  If you're not interested in the default races, you can drop out the Content folder. If you want just the default races, you can drop everything in Content except for the core folder.  We don't have an automated release, so each one (currently) is me basically doing it all by hand.

I'll leave this out here for discussion on how best to implement some sort of automated process, or manual breakup of releases in the future.

**Comment by mixxit** [comment]
brililant thanks!

**Comment by mixxit** [comment]
So i included just the default races as above but i am getting errors about missing default animation controller

Where would I find that in the package archive?

![image](https://user-images.githubusercontent.com/233287/119039740-83b32000-b9ac-11eb-9fb5-bf3d647cdabf.png)

Thanks :-)

**Comment by Jaimi** [comment]
Assets/UMA/Content/Example/Animators/Locomotion.controller

You might want to join the discord, there's a lot of people on there: 
https://discord.gg/6f6Unr9G

**Comment by Jaimi** [comment]
Closing. Will add work item to break out sample data.
