### ISSUE TITLE
LipSync Integration

### ISSUE THREAD

**Issue by cameronedmond** [umasteeringgroup/UMA#359]
Hi there! We are working on a research project at my lab and are looking into UMA as a solution to one of our problems. We are looking for a lipsyncing solution to integrate with the avatars we have created. We are aware of SALSA, but wanted to check if there are any alternatives that the UMA developers recommend? Cheers!

**Comment by Jaimi** [comment]
Salsa and Lipsync Pro are the two most people use. Not sure on the status of Salsa though. You can also use a lipsync system that uses Blendshapes if you use the Blendshape Emulator (or if you add Blendshapes, of course). You may want to join the discord if you haven't already.

**Comment by cameronedmond** [comment]
Awesome, thanks! Yeah, I was a bit stuck on using blendshapes with UMA, but I'm new to blendshapes in general. Do you have a link for the Discord? I can't seem to find it (but I might be dumb).

**Comment by Jaimi** [comment]
Here you go: 
https://discord.gg/5b39djg
