### ISSUE TITLE
New FBX export not updating UMA

### ISSUE THREAD

**Issue by ChaimTeco** [umasteeringgroup/UMA#360]
Hey, I'm encountering an issue and wondering if there is a way to fix this-
I'm using UMA to create a customizable character, the character has all its mesh slots in place and several wardrobe recipes, the mesh is being exported from Blender as an FBX. During my workflow I do new FBX exports and overwrite the current FBX file in my unity project, although the FBX itself seems to update correctly to the new export, the UMA character does not seem to receive the updates. For example: some of the meshes have blendshapes exported with them, in blender I add a new blendshape to that mash and re-export the FBX file, going back into unity the exported mesh/FBX shows the new blendshape but the UMA character (UMARenderer) doesn't show the new blendshape, anyone have this issue or know of any solution?

**Comment by Jaimi** [comment]
Slot creation is not automatic. The FBX will need to run through the slot builder and update the slots.
