### ISSUE TITLE
Slot Creation 

### ISSUE THREAD

**Issue by Lincoln143** [umasteeringgroup/UMA#361]
Every time I try create a new slot, an error code appears:
 (NullReferenceException: Object reference not set to an instance of an object
UMA.UMAAssetIndexer.ReleaseReference (UnityEngine.Object obj) (at Assets/UMA/Core/Scripts/UMAAssetIndexer.cs:1567)
UMA.UMAUpdateProcessor.UpdateSlot (UMA.SlotDataAsset slot) (at Assets/UMA/Core/Editor/Scripts/UMAUpdateProcessor.cs:79)
UMA.Editors.UmaSlotBuilderWindow.CreateSlot () (at Assets/UMA/Core/Editor/Scripts/UmaSlotBuilderWindow.cs:327)
UMA.Editors.UmaSlotBuilderWindow.OnGUI () (at Assets/UMA/Core/Editor/Scripts/UmaSlotBuilderWindow.cs:212)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <756e9f00f78640ec93f83e08257daaec>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <756e9f00f78640ec93f83e08257daaec>:0)
UnityEditor.DockArea.OldOnGUI () (at <756e9f00f78640ec93f83e08257daaec>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <52d042b59b5f4b5fa4d9379442f5155a>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <9ff04fda545c4aacb8dab659ad40b2f4>:0))
i tried using the automatic slot creator but after it says creating slot, its says importing assets, this ran for 15 hours and still nothing happened.

**Environment 
 - Unity Version: 2021.1.5f1
 - UMA Version: 2.12
 - Rendering Pipeline: I'm a using the 3d template I'm not sure what you call this pipeline
 - Platform Build (if not editor): PC 

**To Reproduce**
1. Go to UMA drop down in menu
2. select slot builder
3. Add UMA Material 
4. Add slot destination folder
5. Add slot mesh 
6.  click verify slot ( says no errors found )
7. click create slot 
8. debug log says processing 
9. See error

Expected behavior
I believe a slot needs to be created 

**Screenshots**
![image](https://user-images.githubusercontent.com/51958874/120474868-feb30800-c3a8-11eb-8d6a-c9db4f792bc8.png)

**Comment by Jaimi** [comment]
Somehow this is getting a null slot.  I'm not able to duplicate it, but I added a null check so the exception doesn't get thrown.
