### ISSUE TITLE
BuildCharacter weird behaviour with avatar DoLoad

### ISSUE THREAD

**Issue by Arthur-Kenichi-Condino** [umasteeringgroup/UMA#362]
**Describe the bug**
there's a bug or something that prevents me changing DNA by script (the values change but the character isn't updated): and BuildCharacter() needs to be called twice so the collider is updated correctly when CharacterComplete event is fired. 

The character is saved to (and loaded from) a txt file.

**Environment (please complete the following information):**
 - Unity Version: 2020.3.0f1
 - UMA Version: 2.10
 - Rendering Pipeline: I don't know
 - Platform Build (if not editor): Editor

**To Reproduce**
My scripts which interact with UMA are:
https://github.com/Arthur-Kenichi-Condino/SolitudeV5/blob/homunculus/Assets/AKCondinoO/Characters/System/Character.cs
where I use avatar DoLoad and DoSave, and dna setters and BuildCharacter function

and:
https://github.com/Arthur-Kenichi-Condino/SolitudeV5/blob/homunculus/Assets/AKCondinoO/SimObject.cs
where I created OnCharacterCompleted(UMAData umaData) to handle CharacterCompleted event and OnUMADataChanged() to get collider values; note that OnCharacterCompleted calls BuildCharacter again once, otherwise OnUMADataChanged gets wrong collider values

**Expected behavior**
BuildCharacter should update the UMA character body correctly. It fails to update the body if the character was loaded from a txt file with file system mode. BuildCharacter only works if the file wasn't present at the beginning, when the editor play button is pressed, thus not allowing the call of avatar DoLoad function

**Screenshots**
I don't know

**Additional context**
I try to change all UMA data through script

**Comment by Arthur-Kenichi-Condino** [comment]
currently, I suspect setting recipeString while loading could be affecting next changes to the character. Does anyone know which files use recipeString so I can test:

            Debug.LogWarning("recipeString:"+recipeString);

...? :D

**Comment by Arthur-Kenichi-Condino** [comment]
I found the culprit is DynamicCharacterAvatar.DoLoad(), but I couldn't find a solution yet

**Comment by Jaimi** [comment]
@Arthur-Kenichi-Condino - 

We can probably diagnose this easier on the discord:

https://discord.gg/5b39djg

Are you trying to change the DNA inside the Completed event?

**Comment by Arthur-Kenichi-Condino** [comment]
Are you trying to change the DNA inside the Completed event?
No, I change the DNA on Update, then I call BuildCharacter(); but the character doesn't change its body. I keeps the new DNA values but doesn't change the appearance. And DoSave() doesn't save the new values too. This only happens if DoLoad() is called.

in the Completed event I get the new collider values.

**Comment by Jaimi** [comment]
Closing. Old issue. Please reopen if reappears
