### ISSUE TITLE
null reference exception when adding receipe

### ISSUE THREAD

**Issue by tatmanblue** [umasteeringgroup/UMA#363]
**Describe the bug**
I added a UMADynamicCharacterAvatar to my new scene.  I then dragged MailHair1 recipe and got this error.

```
NullReferenceException: Object reference not set to an instance of an object
UMA.TextureProcessPRO.ProcessTexture (UMA.UMAData _umaData, UMA.UMAGeneratorBase _umaGenerator) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/TextureProcessPro.cs:58)
UMA.UMAGeneratorPro.ProcessTexture (UMA.UMAGeneratorBase _umaGenerator, UMA.UMAData _umaData, System.Boolean updateMaterialList, System.Int32 InitialScaleFactor) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorPro.cs:372)
UMA.UMAGeneratorBuiltin.GenerateSingleUMA (UMA.UMAData data, System.Boolean fireEvents) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:305)
UMA.UMAGeneratorBuiltin.OnDirtyUpdate () (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:454)
UnityEngine.Debug:LogException(Exception)
UMA.UMAGeneratorBuiltin:OnDirtyUpdate() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:476)
UMA.UMAGeneratorBuiltin:Work() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:160)
UMA.UMAGeneratorBuiltin:Update() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:112)
```

I deleted UMAEditorContext game object as well as the UMADynamicCharacterAvatar game object.  I re-added UMADynamicCharacterAvatar and dragged MailJeans1 recipe to the inspector and got the error again.

Once the error appears, the UMA character is no longer rendered.

**Environment (please complete the following information):**
 - Unity Version:  2020.3.10F1.498
 - UMA Version: 2.12
 - Rendering Pipeline: base, I guess.  Not HDR.
 - Platform Build (if not editor): windows 10

**To Reproduce**
see above

**Expected behavior**
Recipe to appear on UMA character and UMA character renders successfully

**Screenshots**

See [https://imgur.com/a/7iN8qJP](https://imgur.com/a/7iN8qJP)

**Additional context**

**Comment by Jaimi** [comment]
Fixed in 2.13.  An editor context is no longer automatically created. instead, you are prompted to add the UMA_GLIB to the scene (either permanently or temporarily).
For now, you can get back to normal by selecting a recipe or character, and while the editor context is created, lock the inspector, select a non-uma item, drop a UMA_GLIB into the scene, and then unlock the inspector.

**Comment by tatmanblue** [comment]
when will 2.13 be available?

**Comment by Jaimi** [comment]
Maybe 3-4 weeks? Depends on a few items. You can get the current test version from the develop branch.
