### ISSUE TITLE
Slot 'MaleEyes' Material Channel 1 refers to material property '_BumpMap' but no such property exists.

### ISSUE THREAD

**Issue by Chris1234567899** [umasteeringgroup/UMA#367]
**Describe the bug**

I get the following errors, right after adding the package:

"Slot 'MaleEyes' Material Channel 1 refers to material property '_BumpMap' but no such property exists."
"Slot 'MaleEyes' Material Channel 2 refers to material property '_MetallicGlossMap' but no such property exists."
"UMAData: Recipe or Generator is not valid!"

**Environment (please complete the following information):**
 - Unity Version: Unity 2021.1.0f1
 - UMA Version: 2.12
 - Rendering Pipeline: HDRP

I tried updating the materials to HDRP afterwards, but it does not help. Tried adding the HDRP-Races unitypackage that are included and run the HDRP Test Scene, but nope, same error happens.

**Comment by lloydcarroll** [comment]
Bump, having same issue.

**Comment by Jaimi** [comment]
Thus is due to not converting the umamaterials to the new srp. I will be providing a set if default shader using Better Shaders ti address this next release. Please join the discord if you need assistance converting the materials.

**Comment by lloydcarroll** [comment]
> 

Awesome, I'll find the discord

**Comment by lloydcarroll** [comment]
> Thus is due to not converting the umamaterials to the new srp. I will be providing a set if default shader using Better Shaders ti address this next release. Please join the discord if you need assistance converting the materials.

Didn't think it would be this hard to find the discord, can you share a link?
