### ISSUE TITLE
DynamicCharacterAvatar prefab is unpacks when saving scene when Editor Time Generation is false

### ISSUE THREAD

**Issue by Arlorean** [umasteeringgroup/UMA#368]
**DynamicCharacterAvatar prefab is unpacks when saving scene when Editor Time Generation is false**
A prefab with a **DynamicCharacterAvatar** component where the **Editor Time Generation** is set to false will unpack itself into a scene when that scene is saved. This shouldn't happen, the prefab should remain in place.

**Environment (please complete the following information):**
 - Unity Version: 2020.2.2f1
 - UMA Version: 2.12
 - Rendering Pipeline: URP 10.2.2
 - Platform Build (if not editor): Editor on Windows (DX11)

**To Reproduce**
1. In Unity Hub Add **Unity 2020.2.2f1** project
2. New URP project
3. Import UMA 2.12 via Package Manager
4. UMA->SRP->Convert to URP
5. UMA->Rebuild From Project
6. File->New Scene->Basic (Built-In)
7. Drag **UMA->Getting Started->UMA_GLIB** into scene
8. In the Project tab, select the prefab **UMA->Getting Started->UMADynamicCharacterAvatar** 
9. In Inspector uncheck **Editor Time Generation** to make it be **false**
10. Drag **UMA->Getting Started->UMADynamicCharacterAvatar** prefab into scene
11. File->Save->NewScene.unity
12. BUG: The **UMADynamicCharacterAvatar** prefab has been unpacked in the scene on Save

**Expected behavior**
It is expected that the prefab will **NOT** unpack itself since we don't want editor time generation of the UMA, only runtime.

**Additional context**
Keeping UMA character prefabs intact is tough going for our artist who keeps breaking them!

**Comment by Jaimi** [comment]
Fixed in previous version.
