### ISSUE TITLE
Newest version does not work in unity 2018.1.0f2

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [umasteeringgroup/UMA#374]
**Describe the bug**
Won't build until I delete the UMA folder

**Environment:**
 - OS: Windows 7 Professional SP1 64 bit
 - Unity Version: 2018.1.0f2
 - UMA Version: 2.12
 - Rendering Pipeline: DX 11 on Nvidia NVS 3100M
 - Platform Build (if not editor): Windows x86_64

**To Reproduce**
1. Download UMA212.unitypackage from releases
2. Install Unity 2018.1.0f2 (only install the editor, documentation, android support, iOS support and Linux support)
3. Open unity 2018.1.0f2
4. Create a new project
5. Rename the scene to Character_creator
6. Use the import button and import the UMA212.unitypackage file
7. Create a Plane
8. Try to build for windows in a folder called "Win 64" inside the project folder
9. Build will fail
10. Delete the UMA folder
11. Try to build again
12. it will work and the built exe runs

**Screenshots**
![Capture](https://user-images.githubusercontent.com/42124824/151874035-66d388c6-9ef3-4763-9785-e1baee947a9e.PNG)

**Comment by Jaimi** [comment]
No longer supported, closing.
