### ISSUE TITLE
DynamicCharacterAvatarEditor behavior when subclassing DCA

### ISSUE THREAD

**Issue by brzGatsu** [umasteeringgroup/UMA#375]
Hi, I made a subclass of DynamicCharacterAvatar and added some properties. However, these properties cannot be set in the editor. THis is because the call "Editor.DrawPropertiesExcluding" in DynamicCharacterAvatarEditor:108 is not surrounded by EditorGUI.BeginChangeCheck() and EditorGUI.EndChangeCheck() + serializedObject.ApplyModifiedProperties().

**Comment by Jaimi** [comment]
Fixed in previous release
