### ISSUE TITLE
Bone not found exception

### ISSUE THREAD

**Issue by brzGatsu** [umasteeringgroup/UMA#376]
I have a wardrobe recipe that hides everything except for the head. UMA perfectly optimizes the unneeded bones away. However, in play mode UMASkeleton::GetRelativePosition is triggered which calls BaseCharacterModifier::UpdateCharacterHeightMassRadius. This triggers a "Bone not found" Exception when trying to access the "Left/RightUpperLeg" boneHashData. The functions of BaseCharacterModifier should handle this gracefully without an exception being thrown by checking first skeleton.BoneExists.

**Comment by Jaimi** [comment]
Fixed in 2.13
