### ISSUE TITLE
when I drag fbx files to slot builder , have a error  and can not creat slots. 

### ISSUE THREAD

**Issue by FzuLiWei** [umasteeringgroup/UMA#379]
**Describe the bug**
when I drag fbx files to slot builder , have a error  and can not creat slots. 

**Environment (please complete the following information):**
 - Unity Version:2019.4.16f1
 - UMA Version: 2.12 on develop
 - Rendering Pipeline: standard
 - Platform Build (if not editor): window

**To Reproduce**
1. Go to 'fbx' files.Fill out common parmeters . and drag to slot builder automatic area. 
2. See error

![slotbuilder1](https://user-images.githubusercontent.com/7477767/162913906-7bf8d0ff-3b6f-4f7c-af83-a6a4b7216a5e.png)

![slotbuilder](https://user-images.githubusercontent.com/7477767/162912512-8f4d83ba-11e9-483b-a2c9-cd5de4ce5846.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by FzuLiWei** [comment]
Did you have some standards for 'fbx' files ？ so I have unknow it and cause to this error.

**Comment by Jaimi** [comment]
Yes - there has to be a "Global" and "Position" bone at the top of the hierarchy. 

I recommend to go to the discord for issues like this.

**Comment by Jaimi** [comment]
This page has the source blend files for the races to show what the skeleton layout needs to look like:

https://github.com/umasteeringgroup/content-pack/tree/master/ContentPack_2.7.0.0/Blender_28

**Comment by FzuLiWei** [comment]
thanks
