### ISSUE TITLE
When I Create a new Race , I have two errors.

### ISSUE THREAD

**Issue by FzuLiWei** [umasteeringgroup/UMA#380]
When I Create a new Race , I have two errors.
1.Error! Boneweights and BonesPerVertex is invalid. The slot must be regenerated. 
2.IndexOutOfRangeException: Index was outside the bounds of the array.

Unity Version:2019.4.16f1
UMA Version: 2.12 on develop
Rendering Pipeline: standard
Platform Build (if not editor): window

![1](https://user-images.githubusercontent.com/7477767/162945673-3d79bde9-9178-47fd-91fc-20d00adbaa5d.png)

![2](https://user-images.githubusercontent.com/7477767/162945691-6c1f3a72-e305-4624-9771-83ccae249e55.png)

![3](https://user-images.githubusercontent.com/7477767/162945706-6bf6a04a-4fd1-4e4d-add4-d219cc1cb82e.png)

![5](https://user-images.githubusercontent.com/7477767/162945716-59bb732f-04b3-4a90-905c-41b3c7021e3f.png)

Is this Model have Bones outside to cause two errors？

**Comment by FzuLiWei** [comment]
![2022 04 13_李炜 1cbfa2cf2dd4ba2fe55786046cab9dd1](https://user-images.githubusercontent.com/7477767/163092397-c1b76157-0cfa-40fe-946f-6af9edd5d382.png)

sorry , I can open it.

**Comment by Jaimi** [comment]
Sorry - did not realize you were in China, and discord is blocked.  
This error is saying that some of the required boneweight data is missing from the SlotDataAsset.Meshdata.

Slots in UMA can have boneweight information in two different places. Old Slots can have that in meshData.BoneWeights. New Slots will have it in two fields: ManagedBoneWeights and ManagedBonesPerVertex.

When an old slot is loaded, the data is read from the old field (meshData.BoneWeights) and put in the new fields.  of course, new slots do not use this translation method.

So somehow you have a slot that does not have bone weights. This is usually not possible with a skinned mesh. It was a bug that happened with an alpha version of 2.11, so if someone generated these slots with an alpha, I could see that being a problem.

What I recommend is to review your "SlotDataAssets" that you are using, and verify that they all have boneweights - either in the MeshData.BoneWeights, or MeshData.ManagedBoneWeights and MeshData.ManagedBonesPerVertex fields.

You can do this by changing the inspector to use "debug" mode by right clicking on the tab. Then you can drill down into the meshdata on the SlotDataAssets, and find the one(s) that is/are broken, and regenerate them.  If that doesn't fix it, we need to look at the slot to see why it is not working.

**Comment by FzuLiWei** [comment]
thanks , I will have a try for it.

**Comment by christopher-genies** [comment]
Any update on this? I am getting the first error. (Error! Boneweights and BonesPerVertex is invalid. The slot must be regenerated). Upon debugging, all slots have bone weights and bones per vertex data.

**Comment by Jaimi** [comment]
Note: This can be caused by slots issues: Old slots with new bones. Running over the buffer limit of 16 bit buffers (you should enable 32 bit buffers), or bad fbx files without weighting for some bones.
