### ISSUE TITLE
I want to use addressable to load UMA ，I need which data to add to addressable.

### ISSUE THREAD

**Issue by FzuLiWei** [umasteeringgroup/UMA#382]
**Describe the bug**
I want to use addressable to load UMA ，I need which datas to add to addressable.

**Environment (please complete the following information):**
 - Unity Version:
 - UMA Version:
 - Rendering Pipeline:
 - Platform Build (if not editor):

all type Datas of below pictures in Global Library should be add to addressable? 
RaceData、Recipe、SlotData、OverlayData、UMAMaterial and so on?

![1](https://user-images.githubusercontent.com/7477767/163541290-d2846041-e03c-4ad3-acb7-ef2863a522f0.png)

Thanks .

**Comment by Jaimi** [comment]
There is a PDF in the UMA folder that steps you through it one by one.  Basically, you do not need to do anything except follow those steps. UMA will manage it.

**Comment by FzuLiWei** [comment]
Thanks for it
