### ISSUE TITLE
Create Mesh Hide Asset and Get a error.

### ISSUE THREAD

**Issue by FzuLiWei** [umasteeringgroup/UMA#385]
I follow Secret Anorak video(UMA 201 - Part 5: Converting Clothing Models) to create Mesh Hide Asset . After operate it and click button Save&Return . Get this  error . 

Unity Version:2020.3.2f1
UMA Version: 2.12 from unity assetstore
Rendering Pipeline: URP
Platform: windows

![2022 05 13](https://user-images.githubusercontent.com/7477767/168254735-4c73bdba-5abf-451c-8f78-22446fb618d5.png)

**Comment by Jaimi** [comment]
Fixed in earlier version. If reappears, please reopen.
