### ISSUE TITLE
Add event to DCA: Character Starting

### ISSUE THREAD

**Issue by brzGatsu** [umasteeringgroup/UMA#386]
I would like to modify the character (DNA, Wardrobe etc.) before it is built. For this it would be great to have a CharacterStarting event that is called in the first line of DynamicCharacterAvatar::Start.

**Comment by Jaimi** [comment]
CharacterStart event was added to DynamicCharacterAvatar.
You can also use the new BuildCharacterBegun event on the DynamicCharacterAvatar for this. It does not happen in start, but is done in the automated build.
