### ISSUE TITLE
DCA Script in inspector disappears

### ISSUE THREAD

**Issue by chakrazulu** [umasteeringgroup/UMA#387]
**Describe the bug**

**Environment (please complete the following information):**
 - Unity Version: 2021.3.3f1
 - UMA Version: 2.12
 - Rendering Pipeline: standard
 - Platform Build (if not editor):

**To Reproduce**
1. Go to DCs prefab and drag it into the hierarchy. 
2. Click on the dynamic character Avatar script and add a wardrobe of your choice. Once you do this the DCA script will minimize and be no longer maximizable. All options then disappear and you have to click on anything in the hierarchy. Once you click back on the UMADCA prefab you can then click on the DCA script and it returns to normal. 

**Expected behavior**
You can expect to click back on the prefab anytime you want to access the Dynamic Character Script or anytime you make a change within the script the options disappears and then you have to click on the prefab again. 

**Screenshots**
![Screen Shot 2022-05-30 at 1 51 05 PM](https://user-images.githubusercontent.com/95590405/171041223-a9d135b5-d5c5-4958-b899-544df08bbabf.png)

**Additional context**
I am on an
![Screen Shot 2022-05-30 at 1 51 05 PM](https://user-images.githubusercontent.com/95590405/171041467-ff60a7f0-22b4-466b-b536-a094deb23f21.png)
 M1 Max laptop running Monterey 12.4

**Comment by Jaimi** [comment]
This was due to a drawing error in the editor.  Fixed in earlier version.
