### ISSUE TITLE
BlendshapeDNAConverters can't work

### ISSUE THREAD

**Issue by SmileChen518** [umasteeringgroup/UMA#394]
**Describe the bug**

**Environment (please complete the following information):**
 - Unity Version: 2020.3.8f1c1
 - UMA Version:2.12
 - Rendering Pipeline:
 - Platform Build (if not editor):windows editor

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
I don't know how to apply blendshape into Uma, there is not any help, so I am here.
Create--uma--dna--controller--add converters(BlendshapeDNAConverters)
Than I don't know how to use it.
There is Uma 301 part 9 creating blendshape DNA video online but it can't work, and I get it was legacy when I want to create a morph set DNA.
Thanks very much.

**Comment by Jaimi** [comment]
Please ask usage questions on Unity forum or on Discord:   https://discord.gg/yVfET6je
