### ISSUE TITLE
UMA Renderer resets Layer to default when cloth recipe is removed

### ISSUE THREAD

**Issue by OldVikingGamer** [umasteeringgroup/UMA#398]
If you have an UMA with the UMA Renderer set to a layer that isn't "default".  When a recipe that uses  cloth is removed from he UMA, the renderer is set to the "default" layer and doesn't respect the layer it was originally set to.

Bug found in 

Unity 2021.3.7f1
UMA 2.12
Render Pipeline HDRP

Editor/Windows

To Reproduce
Steps to reproduce the behavior
1. Set UMARenderer object to a layer that is not the default layer
2. Add cloth recipe
3. remove recipe

Expected behavior
UMARenderer object should have it's original layer

Additional context
 
Problem is in UMARendererAsset.cs, static public void ResetRenderer

Line 84
           renderer.gameObject.layer = 0;

Its hardcoded to 0 instead of the layer that assigned

I have a workaround where I changed the hardcode to the layer assigned.  And it is a bit of  pickle due to static method vs instance value, but it is a bug.  If it never gets fixed...lol I will live

**Comment by OldVikingGamer** [comment]
It may be as simple as commenting out line 84.  I am not sure why that line exists or what it is supposed to do.

**Comment by Jaimi** [comment]
Fixed in feature-13
