### ISSUE TITLE
UMA Data Inspector - Unable to find SlotDataAsset: MaleLegs

### ISSUE THREAD

**Issue by DoubleL2** [umasteeringgroup/UMA#399]
After changing PCs and re-opening project (also upgraded unity) and it asked me about re-indexing. Unfortunately... my reflexes worked faster than my brain and I hit to re-index. I think that's what broke it. I have a client version that is fine and this version is server version. I tried copying the Assets\UMA folder over but that did not fix. Is there another file I can copy over to reset?

**Comment by jaimimcentire** [comment]
You're supposed to reindex when you upgrade unity, as it can generate different GUIDS. That won't cause a problem. If it says you're missing a slot, then perhaps the index file is readonly, or maybe the slot is actually missing?  
Anyway, the index is in Assets\UMA\InternalDataStore\InGame\Resources\AssetIndexer.asset
You can also open the Global Library from the UMA menu, and you should be able to find "MaleLegs" in the slots. It should be on the disk here: Assets\UMA\Content\Core\HumanMale\Slots\Body\UMA_Human_Male_Legs_Slot.asset

**Comment by jaimimcentire** [comment]
Also, probably way easier and faster to get assistance on the discord. The link is in the manual in the UMA folder

**Comment by DoubleL2** [comment]
That worked! Copied that file over. Even though system didn't mark it as read-only there was probably some permission messing it up. so I just replaced.

Thanks, I'm in that discord now lol.. I had accidentally removed when I was cleaning up discord.
