### ISSUE TITLE
Creating a slot, creates 2 slots. 

### ISSUE THREAD

**Issue by michaelt-utherverse** [umasteeringgroup/UMA#400]
When creating a slot, using slot builder, this creates a folder and places 2 slot files in it.

**Environment (please complete the following information):**
 - Unity: 2021.3.20f1
 - UMA Version: 2.12
 - Rendering Pipeline: URP

**To Reproduce**
1. Create a clean unity project, install UMA 2.12
2. , create a new slot.

**Expected behavior**
I would expect UMA to not create 2 duplicate files.

**Screenshots**
![DoubleSlots](https://user-images.githubusercontent.com/128001527/227623479-3a51fda2-f965-45bd-b95a-85c0676e5447.jpg)

**Comment by Jaimi** [comment]
This isn't a bug. This will happen if you have multiple materials on your mesh. You will end up with 2 slots, one with each material. You will need to create an overlay for each material, add both slots to the recipe, and assign the appropriate overlay. Unity does not support more than one material per submesh.

**Comment by Jaimi** [comment]
Thanks for reporting though. You may find it easier to get responses on the discord.

**Comment by michaelt-utherverse** [comment]
> r

Thanks! Where can I find this discord? Google doesn't seem to be giving me a result?

**Comment by Jaimi** [comment]
You're welcome - here it is: https://discord.gg/XJ9u3wGaQ5
