### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by tfsJoe** [umasteeringgroup/UMA#405]
This link is not operational: http://umadocs.secretanorak.com/doku.php?id=start

It appears to produce HTTP response 500, which is an internal server error

**Environment**

Tried with Firefox and Chrome.

**To Reproduce**

1. Visit http://umadocs.secretanorak.com/doku.php?id=start
2. Web page will not render.
3. In Firefox, the web console will show a 500 Internal Server error. In Chrome, the error will be rendered instead of the webpage.

**Expected behavior**
The documentation site should render.

**Comment by IUGeek** [comment]
I want to confirm that this is the case.  I tried it on several versions of Firefox, on two different operating systems (Windows 10 and Ubuntu Linux).  I get a blank page, but I did not get the 500 error.  The console says it is in "Quirks mode".  When I do "View source", it gives me an empty file, which may mean the PHP engine is hitting an error before it can produce any HTML.

**Comment by amantenikko** [comment]
https://web.archive.org/web/20221128210403/http://umadocs.secretanorak.com/doku.php
Not a solution thou

**Comment by valentinwinkelmann** [comment]
Documentation is still down. That's very problematic.. can we just made a GitHub internal Wiki page?

**Comment by Jaimi** [comment]
Moving to github wiki.
