### ISSUE TITLE
Creating a new Overlay Data Asset, it is not possible to set the Size of Textures Channels to insert textures

### ISSUE THREAD

**Issue by Assambra** [umasteeringgroup/UMA#407]
**Describe the bug**
Creating a new Overlay Data Asset, setup the Material but it is not possible to set the texture channels to 2 to insert textures.

**Environment (please complete the following information):**
 - Unity Version: 2022.3.18f1
 - UMA Version: 2.13 alpha 4
 - Rendering Pipeline: standard/none
 - Platform Build (if not editor):

**To Reproduce**
1. Create a new Overlay Data Asset
2. Add some Material
3. Textures Channels -> Size -> insert some value e.g. 2, hit enter 
4. Error 1:  Retrieving array element that was out of bounds
UnityEditor.SerializedProperty:GetArrayElementAtIndex (int) 
5. Error 2: NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorGUILayout.IsChildrenIncluded (UnityEditor.SerializedProperty prop) (at <8e887700cd7e4674989da7b046e8eaa6>:0)

**Comment by Jaimi** [comment]
Fixed in Feature-13 branch
