### ISSUE TITLE
FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

### ISSUE THREAD

**Issue by mustaplatforms** [umasteeringgroup/UMA#439]
- Unity Version:2022.3.31f1
 - UMA Version: UMA 2.13 RC 3

I used the old UMA that I downloaded in the asset store and there was no error message, when I updated via github an error message appeared.

I use UMA for RPG Builder

The Error:
FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
System.Convert.FromBase64CharPtr (System.Char* inputPtr, System.Int32 inputLength) (at <467a840a914a47078e4ae9b0b1e8779e>:0)
System.Convert.FromBase64String (System.String s) (at <467a840a914a47078e4ae9b0b1e8779e>:0)
AvatarDefinition.Base64Decode (System.String base64EncodedData) (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/AvatarDefinition.cs:407)
AvatarDefinition.FromCompressedString (System.String compressed, System.Char seperator) (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/AvatarDefinition.cs:334)
Shadowed.RPGB.UMA.UMADNASaveLoad.LoadDNA () (at Assets/Shadowed/RPGBuilder/UMA/Scripts/Data/UMADNASaveLoad.cs:197)
Shadowed.RPGB.UMA.UMADNASaveLoad.Start () (at Assets/Shadowed/RPGBuilder/UMA/Scripts/Data/UMADNASaveLoad.cs:89)

**Comment by Jaimi** [comment]
Fixed in RC 4. Thanks for the report

**Comment by mustaplatforms** [comment]
https://github.com/umasteeringgroup/UMA/assets/168799883/3f430d72-2155-4396-8009-08c8245c7026

Still Error in RC4
