### ISSUE TITLE
Exporting UMA textures / materials always results in a grey texture. 

### ISSUE THREAD

**Issue by BrooklynDipi** [umasteeringgroup/UMA#441]
**Describe the bug**
Exporting textures from the SkinnedMeshRenderer of an UMA avatar results in grey textures after clean upgrade from v2.13a4 to 2.13 RC 4. This occurs with build in UMA export tools as well as scripts I have written myself. 

**Environment (please complete the following information):**
 - Unity Version: 2022.3.33f1
 - UMA Version: UMA 2.13 RC 4
 - Rendering Pipeline: URP
 - Platform Build (if not editor): 

**To Reproduce**
1. Generate an avatar
2. Navigate to DynamicCharacterAvatar component 
3.  Click the context menu for this component
4.  "Save selected avatars generated textures..."
5. See result of grey textures

**Expected behavior**
Properly exported textures.

**Screenshots**
![image](https://github.com/umasteeringgroup/UMA/assets/44684333/b3d1332e-f8f0-42c7-91ca-90f4356e41c1)
![image](https://github.com/umasteeringgroup/UMA/assets/44684333/cb3c0073-1422-42b4-92de-e6b44d976d2d)

**Additional context**
I have experimented with setting the texture import settings to be 'Readable' as well as making sure 'Convert render textures' are turned on in UMA_GLIB. These changes have not helped.

**Comment by Jaimi** [comment]
Fixed in RC7

**Comment by dan-asa** [comment]
I have the same problem with the last version from asset store, 2.13 RC10 I think. Tried it in Unity 2021.3.31 and 2022.3.19, the base maps are all grey.

**Comment by BrooklynDipi** [comment]
> I have the same problem with the last version from asset store, 2.13 RC10 I think. Tried it in Unity 2021.3.31 and 2022.3.19, the base maps are all grey.

I had to do some funky stuff that I didnt have to do previously to get things working on this version, even post fix. Can be seen here


```
private Texture2D GetReadableTexture(Texture2D texture)
    {
        RenderTexture tmp = RenderTexture.GetTemporary(
            texture.width,
            texture.height,
            0,
            RenderTextureFormat.Default,
            RenderTextureReadWrite.Linear);

        Graphics.Blit(texture, tmp);
        RenderTexture previous = RenderTexture.active;
        RenderTexture.active = tmp;

        Texture2D readableTexture = new Texture2D(texture.width, texture.height);
        readableTexture.ReadPixels(new Rect(0, 0, tmp.width, tmp.height), 0, 0);
        readableTexture.Apply();

        RenderTexture.active = previous;
        RenderTexture.ReleaseTemporary(tmp);

        return readableTexture;
    }
