### ISSUE TITLE
IndexOutOfRangeException when modifying Texture Channels in UMA Material

### ISSUE THREAD

**Issue by jurjjc** [umasteeringgroup/UMA#444]
**Describe the bug**
When decreasing the "Texture Channels" by 1 and then increasing it by 1 in UMA Material, an IndexOutOfRangeException occurs. 

**Environment (please complete the following information):**
 - Unity Version: 2022.3.32
 - UMA Version: UMA 2.13 RC 7
 - Rendering Pipeline: URP
 - Platform Build (if not editor): Android

**To Reproduce**
1. Select a UMA material.
2. In the Inspector, locate the "Texture Channels" section.
3. Decrease the "Texture Channels" value by 1.
4. Increase the "Texture Channels" value by 1.
5. Observe the Console for the error.

**Expected behavior**
Modifying the "Texture Channels" value should not cause any errors.

**Screenshots**

**Additional context**

**Comment by Jaimi** [comment]
I'm not able to duplicate this. Can you post the error and the call stack?

**Comment by jurjjc** [comment]
IndexOutOfRangeException: Index was outside the bounds of the array.
UMA.Editors.UMAMaterialInspector.IsChannelValid (System.Int32 channel) (at Assets/UMA/Core/Editor/Scripts/UMAMaterialInspector.cs:224)
UMA.Editors.UMAMaterialInspector.DrawChannelList (UnityEditor.SerializedProperty list, UMA.UMAMaterial+MaterialType materialType) (at Assets/UMA/Core/Editor/Scripts/UMAMaterialInspector.cs:261)
UMA.Editors.UMAMaterialInspector.OnInspectorGUI () (at Assets/UMA/Core/Editor/Scripts/UMAMaterialInspector.cs:158)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass72_0.<CreateInspectorElementUsingIMGUI>b__0 () (at <3d611f181d2047d0a4666e5262482490>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by Jaimi** [comment]
This appears to be a case where the object has not yet been updated by the SerializedProperty, and the channel was expanded before the object was updated. I forced the SerializedObject to ApplyModifiedProperties before drawing the channel list, and then checked the array bounds before accessing the channels. Checked into Feature-13 branch, will be in next RC or Release.

**Comment by Jaimi** [comment]
Feature-13
