### ISSUE TITLE
Unity 6 HDRP 17 UMA Skin Shader Errors

### ISSUE THREAD

**Issue by azcoffeehabit** [umasteeringgroup/UMA#452]
**Describe the bug**
Shader Errors in HDRP 17 on the Skin Shader.

UMA/Diffuse_Normal_Metallic (Shader)
"Undefined punctual shadow filter algorithm"
invalid subscript "decalLayerMask"

**Environment (please complete the following information):**
 - Unity Version:  Unity 6.0.16f1
 - UMA Version: Latest Release / Dev branch
 - Rendering Pipeline:  HDRP 17
 - Platform Build (if not editor):

**To Reproduce**
1. Create New Project  Unity 6
2. Select HDRP Empty Scene
3. Drag in Getting Started resources
4. UMA skin will be oddly shaded when placed against an "outdoor scene" background 

**Expected behavior**
The UMA will be properly lit against HDRP background

**Screenshots**
![image](https://github.com/user-attachments/assets/d104e9d9-afc2-47fc-9df0-062b35647683)

![image](https://github.com/user-attachments/assets/603660e7-b22f-4373-96e8-5fea80ae23b3)

**Comment by Jaimi** [comment]
Completed in Feature-13
