### ISSUE TITLE
Tag UMAKeepChain is not created in new Unity 6 Project 

### ISSUE THREAD

**Issue by azcoffeehabit** [umasteeringgroup/UMA#453]
**Describe the bug**
the Unity Tag UMAKeepChain is not created in new Unity 6 Project

**Environment (please complete the following information):**
 - Unity Version: 6000.0.16f1
 - UMA Version:  2.13 (develop branch)
 - Rendering Pipeline:  HDRP
 - Platform Build (if not editor):

**To Reproduce**
Create a new Unity Project
Set up UMA per Getting Started
The Tag UMAIgnore is created
The Tag UMAKeepChain is not created

**Expected behavior**
The Tag UMAKeepChain is created

**Screenshots**
![image](https://github.com/user-attachments/assets/57778b0b-bb1d-4aff-baec-7c9c9ce7d591)
![image](https://github.com/user-attachments/assets/3305e362-9e72-4831-a1d8-2d6f0c4210c8)

**Additional context**

**Comment by azcoffeehabit** [comment]
Manually creating a new Tag UnityKeepChain in the Unity Editor fixes the Console Error

**Comment by Jaimi** [comment]
This is due to having already opened the current unity version in another version of the Unity Editor.  I am reworking the preferences into project settings to address this.

**Comment by Jaimi** [comment]
Moved settings from prefs (system wide) to project settings (project specific).
