### ISSUE TITLE
male avatar has a piggynose

### ISSUE THREAD

**Issue by azcoffeehabit** [umasteeringgroup/UMA#455]
**Describe the bug**
male avatar has a piggynose

**Environment (please complete the following information):**
 - Unity Version: 6000.0.16f1
 - UMA Version: 2.14
 - Rendering Pipeline: HDRP
 - Platform Build (if not editor): win64

**To Reproduce**
Create a default UMA Male and attach an emoting system.   Nose bone seems to be attached to the Mouth Open.   When removed the nose is ok when talking.

**Expected behavior**
He shouldnt have piggyface

**Screenshots**
![image](https://github.com/user-attachments/assets/7fffc72b-19fa-4a28-b2cb-a5521e92cb5c)

**Additional context**
before
https://youtu.be/0ARiaOVv8Z0

after
https://youtu.be/g62mHMnObNw

youtube video of the snarl piggynose

**Comment by Jaimi** [comment]
Removed nosebase. Will be in next update. Thanks!
