### ISSUE TITLE
MeshHideAsset: Select/Unselect modes toggle broken 

### ISSUE THREAD

**Issue by nakedfighter3d** [umasteeringgroup/UMA#457]
In the **MeshHideAsset** editor **"Selecting Mode"** toggle is doing nothing. Expected behavior: when you click & drag creating a square selection in "Select" mode it selects polygons. When you do the same in "Unselect" mode it removes the selection from the previously created selection. That's how it was working in old UMA releases. Currently, it always behaves as in "Select" mode. Toggle didn't change anything. 

Tested in several recent 2.13 releases. Unity 2021.3 LTS

**Comment by Jaimi** [comment]
I can't duplicate this. I tracked the code through and those buttons set a bool value that is directly plugged into the bit array. I assume this is probably some addon (like Odin Inspector?) is constantly recreating the editor (it does that, it's weird). Anyway, I made the variables static, so it should survive being recreated, hopefully this will fix it if that is the problem.
