### ISSUE TITLE
Request for character restriction and avatar selection

### ISSUE THREAD

**Issue by Romulan4** [umasteeringgroup/UMA#458]
Hello there :)

I`m a complete newbie in this topic so I hope I can get some help (there was no possibility to contact the support team).
I`m researching avatar solutions for a university project. The functionality UMA 2 offer seems like a great fit for our project.

I have a few questions about the plugin:

- Is it possible to upload complete characters that players can select from without customizing the entire avatar?
- Or can the customization options be restricted to certain aspects (e.g., hair or eye color) while locking other features like skin tone or body shape? 

According to Chat GPT UMA2 offers both, but I need some kind of proof or confirmation, so I hope you can help me. 

Thank you very much.

**Comment by Jaimi** [comment]
Hi - you can design characters and save them to a string. You can present these characters to your players however you want. You can setup what you allow to be customized. A sample scene ships with the plugin that shows how to do this and contains a customizable customized. ;)
Questions like this are more easily answered in the discord channel. An invite is included in the documentation.

**Comment by Jaimi** [comment]
No bug, closing
