### ISSUE TITLE
Slot preview can't handle more than 65k vertices.

### ISSUE THREAD

**Issue by nakedfighter3d** [umasteeringgroup/UMA#460]
Apparently, slot "preview" can't handle more than 65k vertices in the slot asset. Despite the **"Use 32bit buffers"** being enabled in the project and these huge slots can be perfectly used by UMA in general, clicking on this "big" slot in the editor will drop millions of errors. 

`ArgumentException: The number of vertices in the combined mesh (279051) exceeds the maximum supported vertex count (65535) of the UInt16 index format. Consider using the UInt32 IndexFormat for the combined mesh to increase the max vertex count.
UnityEngine.Mesh.CombineMeshes (UnityEngine.CombineInstance[] combine, System.Boolean mergeSubMeshes, System.Boolean useMatrices, System.Boolean hasLightmapData) (at <91dc399f41a440558c716315c7e834ab>:0)
SlotToMesh.ConvertSlotToMesh (UMA.SlotDataAsset slot, UnityEngine.Quaternion Rotation, System.Int32 VertexHighlight) (at Assets/UMA/Core/Editor/SlotToMesh.cs:236)
UMA.Editors.SlotDataAssetInspector.GetPreviewMesh () (at Assets/UMA/Core/Editor/Scripts/SlotDataAssetInspector.cs:530)
`

**Fast solution:**
in `SlotToMesh.cs` at line 236 instead of `Mesh combinedMesh = new Mesh();` we can explicitly declare 
`Mesh combinedMesh = new Mesh{indexFormat = IndexFormat.UInt32};` 

Mesh preview will still be limited to the 65k vertices _(apparently mesh processing uses int16 somewhere before as well)_ but at least we will not have big red errors in the console.

**Comment by Jaimi** [comment]
Fixed in Feature-13 branch - will be in next update
