### ISSUE TITLE
Dynamic UMA stuff is not removable without an error

### ISSUE THREAD

**Issue by DirtyHippy00** [umasteeringgroup/UMA#5]
Since the dynamic avatar stuff is an extension, and has a bunch of stuff I don't need, I removed it.

However, it looks like UMACustomization uses a script that is in the dynamic avatar extension (MouseOrbitImproved).  Likely this script should be moved out of dynamic avatar into Core UMA so the extension can be removed without issue.

**Comment by virror** [comment]
Looking into this and noticing there are more issue than just that script.
Working on it.

**Comment by Jaimi** [comment]
Dynamic DNA is moved into the main and is now the default. Closing.
