### ISSUE TITLE
Dynamic DNA Recipes Crash Unity Editor in Unity 5.6

### ISSUE THREAD

**Issue by SecretAnorak** [umasteeringgroup/UMA#6]
Nasty Bug in 5.6: Selecting HumanMaleDCS and HumanFemaleDCS race crash the editor........!

Repro steps:
- Fresh project in Unity 5.6
- Download UMA (from store)
- Add UMA_DCS prefab to the scene
- Make a new Gameobject and attach DCS component
- Set Race to HumanMaleDCS or HumanFemaleDCS
- Run
- Pow,........... Crash To Desktop.....!

Works fine if you use plain old HumanMale or HumanFemale
Also works correctly in 5.5.1f1

Looks like 5.6 broke something with Dynamic DNA..........

**Comment by virror** [comment]
Fixed by: cff695240b1c843f9135a9ca59cc80b6be08b092
