### ISSUE TITLE
Created avatars moving forward or backward

### ISSUE THREAD

**Issue by tomaszzackiewicz** [umasteeringgroup/UMA#7]
Hi,

I imported the UMA Master project to Unity 5.6 (Windows 10) and created avatars behave strange in my project. I open the example scenes in the UMA project and the created avatars moving forward or backward slightly jumping. 

Here movies:

[MovingAvatars.zip](https://github.com/umasteeringgroup/UMA/files/905184/MovingAvatars.zip)

EDIT: I have just found that this strange behaviour is because of a rigidbody. When I remove this components from avatars, they stop to move and jump. Any idea?

The avatar stops when I check Is Kinematic in his rigidbody.

**Comment by virror** [comment]
I would personally not recommend using a rigidbody for characters because the physics in Unity is just not stable enough so you will run into all kinds of strange behaviors. Better use Unitys character controller scripts that simulate gravity only, gives a lot better results in this case. I highly doubt this is a bug related to UMA itself.

**Comment by tomaszzackiewicz** [comment]
But I have troubles with using your avatars. Rigidbody is added automatically, probaby by one of your script. How to do to remove a rigidbody from UMA avatars?

**Comment by virror** [comment]
Ok, i thought you had added them yourself, sorry about that. You just play the example scene with no changes at all?

**Comment by tomaszzackiewicz** [comment]
No changes. I play some example scenes and UMA avatars get some components at runtime (procedurally). One of them is a rigidbody. And they start to move like in the movies. I can stop them by removing rigidbodies in game or checking Is Kinematic. I don't need the rigidbodies. How to remove them or do other fixes? Which script does that?

**Comment by tomaszzackiewicz** [comment]
I would like to use the example scene UMA DCS Demo - Using Asset Bundles in my project, but the avatars go crazy. I think to remove the rigidbodies. Do I need them?

**Comment by virror** [comment]
Its the CapsuleCollider slot that adds one, you can find it here:
https://dl.dropboxusercontent.com/s/viaaokw7hxx9dyu/shot_170407_111840.jpg

Just set the array size to 0 and it should go away.

**Comment by tomaszzackiewicz** [comment]
Ok, it works, but the problem is that now our avatars have no capsule. I cannot click on them. Is there other way to fix that?

**Comment by virror** [comment]
I guess you can put that back then and change the code in CapsuleColliderSlotScript.cs and remove the first block of code dealing with adding a rigidBody, might be easiest.

**Comment by tomaszzackiewicz** [comment]
Oh, yes, now much better! What's wrong with those avatars? Is it an Unity bug?

**Comment by virror** [comment]
I have never heard of this issue before, and we had plenty of ppl run the example scenes. I think it must be some strange Unity bug. What version of Unity are you using?

**Comment by tomaszzackiewicz** [comment]
Unity 5.6 Personal. I downloaded UMA Master to my computer and ran in a separate project. All is OK. But as soon as I added it to my previous project (upgraded to Unity 5.6), I noticed this strange behaviour. I had a previous version of UMA and I removed it. Really, I made no manipulation in UMA. I just started the example scenes. In some of them, no this behaviour.

**Comment by tomaszzackiewicz** [comment]
Thank you for help!
