### ISSUE TITLE
Copying a DCA component at runtime, creates an Unusable UMA

### ISSUE THREAD

**Issue by SecretAnorak** [umasteeringgroup/UMA#72]
Say for example I run and start adding clothes to the default wardrobe. I'm happy with my outfit and colours so to save time I decide to copy the component, quit and paste values back to my DCA,..... should work yes?

No,... the resulting UMA has no wardrobe slots and will no longer accept wardrobe slots.

Same happens if I paste as a new component.

**Comment by kenamis** [comment]
I think would be near impossible to do, there's too much checking going on in the DCA to support copy and paste. @Jaimi ?

**Comment by Jaimi** [comment]
Yeah, while it seems like it would be nice in some cases, it's sort of dependent on how Unity has implemented copy/paste. As a workaround, the load/save can be used from the menu.
