### ISSUE TITLE
Switching active race throws exception. (Under some conditions)

### ISSUE THREAD

**Issue by SecretAnorak** [umasteeringgroup/UMA#73]
Error occurs if you are looking at the slot list in the UMAData Component while you swap active race. 

After a couple of swaps editor throws an exception with the following messages:

> ArgumentException: Getting control 12's position in a group with only 12 controls when doing Repaint
> Aborting

> GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Jaimi** [comment]
Fixed by DOS in develop branch.
