### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by tomaszzackiewicz** [umasteeringgroup/UMA#8]
Hi,

I downloaded UMA 2.6 to my project (Unity 5.6) and tried to build I got the error:

NullReferenceException
UMA.UMAAssetIndexer.ForceSave () (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs:199)
UMA.UMAAssetIndexer.UnityEditor.Build.IPreprocessBuild.OnPreprocessBuild (BuildTarget target, System.String path) (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs:804)
UnityEditor.Build.BuildPipelineInterfaces.OnBuildPreProcess (BuildTarget platform, System.String path, Boolean strict) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:232)
UnityEditor.HostView:OnGUI()

Assets/UMA/Examples/Extensions Examples/DynamicCharacterSystem/Scripts/Scene4/PhotoBooth.cs(645,0): error CS1525: Unexpected symbol `}'

![builderror](https://cloud.githubusercontent.com/assets/5631906/24829841/bfd4dbf2-1c79-11e7-9cc0-fc6d636899ee.jpg)

I must say that in the UMAAssetIndexer script I added lines:

```
#if UNITY_EDITOR
using UnityEditor.Build;
#endif
```

because when I downloaded UMA to Unity, I got errors and suggestion to add "using UnityEditor.Build".

**Comment by virror** [comment]
uma26 branch is not really recommended for development atm because there are a lot of changes going in and it can be pretty unstable. Thanx for the report though : )

**Comment by tomaszzackiewicz** [comment]
The same with UMA 2.5 :). I got the same error when I downloaded UMA 2.5 to Unity. The suggestion to add "using UnityEditor.Build". So I wrote the code above and it worked. But I don't know if I could build because I have troubles with both UMA 2.5 and UMA 2.6. I just copied the stuff from the  "UMA DCS Demo - using Asset Bundles" scene to my scene and the UI doesn't work. How to fix that?

**Comment by tomaszzackiewicz** [comment]
It seems that I fiexed the problem in the PhotoBooth file. I just moved 
`#endif`

at the end of the file to include all the file content. This file is editor-only.

Now, I get a few errors from UMAAssetIndexer.

**Comment by tomaszzackiewicz** [comment]
I removed UNA 2.6 and downloaded the Master branch. Wow, now all seems great! You added the line:
`using UnityEditor.Build;`
And I can build UMA in a separate project. I got only the error:

ullReferenceException
UMA.UMAAssetIndexer.ForceSave () (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs:201)
UMA.UMAAssetIndexer.UnityEditor.Build.IPreprocessBuild.OnPreprocessBuild (BuildTarget target, System.String path) (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs:814)
UnityEditor.Build.BuildPipelineInterfaces.OnBuildPreProcess (BuildTarget platform, System.String path, Boolean strict) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:232)
UnityEditor.HostView:OnGUI()

I will try it out in my scene.

**Comment by tomaszzackiewicz** [comment]
I included UMA in my project and copied the stuff from the "UMA DCS Demo - using Asset Bundles" scene to my scene. I need that in my project. I can build without errors but WHERE THE FUCK IS MY AVATARS?!!!
![noavatars](https://cloud.githubusercontent.com/assets/5631906/24835588/811ccc84-1d06-11e7-83df-aaab5049d244.jpg)
I use Vulkan API.
In the Unity Editor, I see the avatars, can click on them and the UI is showed, but the UI doesn't work. I cannot change hair, clothes, colors, etc.

**Comment by tomaszzackiewicz** [comment]
I have just tested the build of the "UMA DCS Demo - using Asset Bundles" scene in the separate project with UMA only and the same problem, but I clicked the Debug button and I got the errors:

![noavatarerrors](https://cloud.githubusercontent.com/assets/5631906/24835700/9d63337c-1d08-11e7-9d85-6d77e39d5778.png)

**Comment by tomaszzackiewicz** [comment]
I downloaded UMA 2.5.1 (Unity 5.6).

Still error:
![image](https://cloud.githubusercontent.com/assets/5631906/24874269/6044277c-1e24-11e7-8eda-d56dc0cf3708.png)

**Comment by kenamis** [comment]
Can you go to the global library
![image](https://cloud.githubusercontent.com/assets/3794587/24875388/b39414fc-1ddc-11e7-8ad9-050e0f266e2b.png)

and see if "Eye Overlay" is in there

![image](https://cloud.githubusercontent.com/assets/3794587/24875455/f47554a4-1ddc-11e7-95c5-a78bec502f0c.png)

**Comment by tomaszzackiewicz** [comment]
![image](https://cloud.githubusercontent.com/assets/5631906/24875618/fcb20d82-1e28-11e7-8afc-e532f4409caa.png)

I thin it's all Ok.

**Comment by kenamis** [comment]
but you still get the error or is the scene working now?

**Comment by tomaszzackiewicz** [comment]
I can run the scene in Editor. No problems. I'll try to build the example scene again.

**Comment by tomaszzackiewicz** [comment]
The result:
![noavataragain](https://cloud.githubusercontent.com/assets/5631906/24875817/a43bc048-1e29-11e7-83e3-a4f4b8408628.png)

**Comment by tomaszzackiewicz** [comment]
The same error.

**Comment by tomaszzackiewicz** [comment]
![umaerroragain](https://cloud.githubusercontent.com/assets/5631906/24875876/e2395a54-1e29-11e7-891c-c298ce34733c.png)

**Comment by tomaszzackiewicz** [comment]
The error is alwalys in the build, not in Editor. Really strange.

**Comment by kenamis** [comment]
Yes, I see that now.  That does happen for me too, I'm trying to fix it now.

**Comment by tomaszzackiewicz** [comment]
Ok.

**Comment by kenamis** [comment]
I think we have fixed it if you can try and update from master again.

**Comment by tomaszzackiewicz** [comment]
Thank you - now it works.

However, still I have problem with the copied stuff from the example scene to my scene. I wrote on the forum thread.

**Comment by kenamis** [comment]
Which is that you're trying to copy the UI stuff to a new scene?

**Comment by tomaszzackiewicz** [comment]
This is what I wrote on the UMA forum thread:

Yes, I have no big knowledge about UMA because I use a different software, but this time I need this scene for my project. I have installed the fixed version of UMA 2.5.1 and all great. But when I copied the stuff from the "UMA DCS Demo - using Asset Bundles" scene making a prefab and then place the prefab in my scene, again the UI doesn't work. The three avatars are DCS.

EDIT: I noticed a strange thing:

The options for Race, Wardrobe, Colors, etc. appear only in the Scene View, not in Play view! For example, I click on the Race button and the options for choosing the race doesn't appear in the Game window, only visible in the Scene window. And when I click on the UI element (the root for all UI elements) that is a canvas, it moving upward and downward in the Scene view. I think it is problem with UI, not with AssetBundles or races.

And when I click on an UI item, a Blocker appears in my Scene Hierarchy.

**Comment by kenamis** [comment]
Well, that is outside of the scope of bug fixes for UMA, but did you make sure to copy over "DynamicSampleCustomizer" also?  

I don't think the UI was made with it in mind to be able to copy to other scenes.  I recommend examining the UI to understand how it works.  Also, could you not copy the whole scene and then modify it for your project?

**Comment by tomaszzackiewicz** [comment]
I just grabbed all the stuff from the example scene (without EventSystem because I have one in my scene) and place the prefab in my scene. All works in a separate project with UMA only, but the problems are in my project only. I think it is not a problem with UMA itself, but something with UI. 

OK, thank you for your help. Please close the issue. UMA is working great.

**Comment by tomaszzackiewicz** [comment]
Unity Team confirmed that the problem with the UMA UI is caused by a canvas bug in Unity, not UMA itself.
