### ISSUE TITLE
Error on latest 2.5

### ISSUE THREAD

**Issue by JasonWeise** [umasteeringgroup/UMA#9]
Hi

I have just finished downloading the lastet build of UMA 2.5 (Commit: 2f407e93525282cfbc2fc5d3cefce561e52ab147) and am receiving the following errors:

```
Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs(18,8): error CS0246: The type or namespace name `IPreprocessBuild' could not be found. Are you missing `UnityEditor.Build' using directive?
Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs(799,9): error CS0246: The type or namespace name `IOrderedCallback' could not be found. Are you missing `UnityEditor.Build' using directive?
Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs(807,10): error CS0246: The type or namespace name `IPreprocessBuild' could not be found. Are you missing `UnityEditor.Build' using directive?
```
This is with a clean project only containing UMA on Unity 5.6.0f3

Do you have any suggestions?

**Comment by JasonWeise** [comment]
Never mind, 5.6 just requires the following:
```
using UnityEditor.Build;
```

I should have not been so lazy..

**Comment by Jaimi** [comment]
This should have been fixed already, but we had to back out some changes, so probably just got reverted. I'll fix it again.

**Comment by Jaimi** [comment]
Ok - got the fix checked in. Sorry about that.
