### ISSUE TITLE
[Development branch] UMA Core Demo - Crowd Recipes not working on Unity 2017.3

### ISSUE THREAD

**Issue by mikaelhogstrom** [umasteeringgroup/UMA#98]
Getting this error at startup:
UMAResourceNotFoundException: SlotLibrary: Unable to find: F_High poly head
UMA.SlotLibrary.InstantiateSlot (System.String name) (at Assets/UMA/Core/Scripts/SlotLibrary.cs:91)
UMA.UMAContext.InstantiateSlot (System.String name) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAContext.cs:119)
UMA.UMAPackedRecipeBase.UnpackRecipeVersion3 (UMA.UMARecipe umaRecipe, UMA.UMAPackRecipe umaPackRecipe, UMA.UMAContext context) (at Assets/UMA/Core/Scripts/UMAPackedRecipeBase.cs:936)
UMA.UMAPackedRecipeBase.UnpackRecipe (UMA.UMARecipe umaRecipe, UMA.UMAPackRecipe umaPackRecipe, UMA.UMAContext context) (at Assets/UMA/Core/Scripts/UMAPackedRecipeBase.cs:35)
UMA.UMAPackedRecipeBase.Load (UMA.UMARecipe umaRecipe, UMA.UMAContext context) (at Assets/UMA/Core/Scripts/UMAPackedRecipeBase.cs:20)
UMA.UMATextRecipe.Load (UMA.UMARecipe umaRecipe, UMA.UMAContext context) (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/pUMATextRecipe.cs:178)
UMA.UMARecipeBase.GetCachedRecipe (UMA.UMAContext context) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMARecipeBase.cs:51)
UMA.Examples.UMARecipeMixer.IncludeRecipe (UMA.UMARecipeBase recipe, UMA.UMARecipe umaRecipe, UMA.UMAContext context, Boolean dontSerialize) (at Assets/UMA/Examples/Main Examples/Scripts/UMARecipeMixer.cs:105)
UMA.Examples.UMARecipeMixer.FillUMARecipe (UMA.UMARecipe umaRecipe, UMA.UMAContext context) (at Assets/UMA/Examples/Main Examples/Scripts/UMARecipeMixer.cs:92)
UMA.Examples.UMARecipeCrowd.RandomizeRecipe (UMA.UMAData umaData) (at Assets/UMA/Examples/Main Examples/Scripts/UMARecipeCrowd.cs:182)
UMA.Examples.UMARecipeCrowd.GenerateOneCharacter () (at Assets/UMA/Examples/Main Examples/Scripts/UMARecipeCrowd.cs:148)
UMA.Examples.UMARecipeCrowd.Update () (at Assets/UMA/Examples/Main Examples/Scripts/UMARecipeCrowd.cs:69)

**Comment by kenamis** [comment]
I can test it later when I get home, but is it not that you just need to add that slot to the global library?

**Comment by kenamis** [comment]
I updated to unity 2017.3 and ran that scene.  I see the error too.  In that scene, it's using the old libraries still.  You can add "UMA_Human_Female_Head_Mid_Slot", located at "Assets/UMA/Content/UMA_Core/HumanFemale/Slots/Body/MidPoly", to the slot library and the scene runs.

**Comment by mikaelhogstrom** [comment]
Ok, great thanks! Unfortunately I couldn't use UMA as I was planning to build a little something for Hololens but I'll look into it again later when I have time.

**Comment by kenamis** [comment]
I'm going to go ahead and close this.  Let us know if it's still an issue for you.
